{
  "hash": "8148fbadd6ae7ca734a486b0344be26c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clasificación: cancelación de reservas hoteleras\"\nsubtitle: \"EJERCICIO DE CLASIFICACIÓN — Regresión logística vs. árbol de decisión\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir si una reserva de hotel se cancelará (`cancelo`: si/no) a partir de las características de la reserva y del cliente. Compararemos dos clasificadores sobre el mismo flujo: una **regresión logística** (lineal e interpretable vía coeficientes) y un **árbol de decisión** (que aprende reglas legibles del tipo \"si la anticipación supera X días y el canal es OTA, entonces...\"). El dataset tiene muchas variables categóricas, así que la receta usará *dummies*; además, `pais_origen` trae faltantes que imputaremos por la moda. Recorremos el flujo completo: partición, receta, `workflow()`, validación cruzada, tuning y evaluación honesta con `last_fit()`, y cerramos con una recomendación clara.\n\n## 1. Cargar librerías\n\nCargamos todo al inicio. `rpart` es el motor que `parsnip` usa por detrás para el árbol de decisión; `rpart.plot` dibuja el diagrama del árbol entrenado, y `corrplot` la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(rpart)\nlibrary(rpart.plot)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nRemovemos `id_reserva` (identificador, no predictor) y convertimos la objetivo a `factor`. Fijamos `\"si\"` como **primer nivel**: `yardstick` toma el primer nivel como el evento de interés, de modo que sensibilidad, AUC y demás métricas se calculen sobre \"canceló = si\", que es justo lo que el hotel quiere anticipar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removemos id_reserva (identificador). Convertimos la objetivo a factor con\n# \"si\" (canceló) como PRIMER nivel = evento de interés.\nreservas <- read_csv(\"reservas_hotel.csv\") %>%\n  select(-id_reserva) %>%\n  mutate(cancelo = factor(cancelo, levels = c(\"si\", \"no\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(reservas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,500\nColumns: 18\n$ dias_anticipacion          <dbl> 103, 75, 48, 33, 123, 78, 47, 110, 32, 75, …\n$ num_noches                 <dbl> 2, 4, 2, 4, 6, 9, 1, 2, 4, 2, 5, 3, 2, 1, 1…\n$ num_noches_finde           <dbl> 1, 2, 1, 2, 2, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0…\n$ num_adultos                <dbl> 3, 1, 1, 2, 3, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2…\n$ num_ninos                  <dbl> 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0…\n$ num_solicitudes_especiales <dbl> 2, 0, 0, 0, 1, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0…\n$ num_estancias_previas      <dbl> 2, 1, 1, 0, 1, 2, 0, 5, 1, 1, 1, 2, 2, 0, 0…\n$ precio_total_mxn           <dbl> 22426, 17112, 21188, 15251, 16123, 22339, 9…\n$ descuento_aplicado_pct     <dbl> 0.4, 9.9, 1.2, 6.8, 5.0, 0.0, 30.7, 0.0, 4.…\n$ tipo_habitacion            <chr> \"estandar\", \"estandar\", \"junior\", \"estandar…\n$ canal_reserva              <chr> \"agencia\", \"ota\", \"ota\", \"agencia\", \"ota\", …\n$ regimen                    <chr> \"desayuno\", \"todo_incluido\", \"media_pension…\n$ temporada                  <chr> \"media\", \"alta\", \"baja\", \"baja\", \"alta\", \"m…\n$ forma_pago                 <chr> \"deposito_50pct\", \"en_hotel\", \"en_hotel\", \"…\n$ pais_origen                <chr> \"europa\", \"mexico\", \"mexico\", \"mexico\", \"me…\n$ cliente_recurrente         <chr> \"si\", \"si\", \"si\", \"no\", \"si\", \"si\", \"no\", \"…\n$ tiene_promocion            <chr> \"si\", \"si\", \"si\", \"si\", \"si\", \"no\", \"si\", \"…\n$ cancelo                    <fct> no, si, no, si, si, no, no, no, no, no, no,…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nTres revisiones mínimas antes de modelar: el **balance de clases**, los **datos faltantes** y la **colinealidad** entre numéricas.\n\nEl balance importa porque, si una clase fuera muy rara, el *accuracy* dejaría de ser confiable (predecir siempre la mayoría daría un accuracy alto pero inútil). Aquí veremos que está razonablemente balanceado, así que el AUC será nuestra métrica de decisión.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreservas %>%\n  group_by(cancelo) %>%\n  count() %>%\n  ungroup() %>%\n  mutate(porcentaje = 100 * (n / sum(n)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|cancelo |   n| porcentaje|\n|:-------|---:|----------:|\n|si      | 608|   40.53333|\n|no      | 892|   59.46667|\n\n</div>\n:::\n:::\n\n\nContamos los `NA`: esto guía la imputación. Esperamos faltantes en `pais_origen` (variable categórica), que imputaremos por la moda.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreservas %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable                   | n_na|\n|:--------------------------|----:|\n|descuento_aplicado_pct     |   75|\n|precio_total_mxn           |   60|\n|pais_origen                |   45|\n|dias_anticipacion          |    0|\n|num_noches                 |    0|\n|num_noches_finde           |    0|\n|num_adultos                |    0|\n|num_ninos                  |    0|\n|num_solicitudes_especiales |    0|\n|num_estancias_previas      |    0|\n|tipo_habitacion            |    0|\n|canal_reserva              |    0|\n|regimen                    |    0|\n|temporada                  |    0|\n|forma_pago                 |    0|\n|cliente_recurrente         |    0|\n|tiene_promocion            |    0|\n|cancelo                    |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación revela colinealidad entre las variables numéricas (por ejemplo, número de noches y monto total suelen ir de la mano). Filtraremos las redundantes con `step_corr()` para que la logística no se confunda con información duplicada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatriz_correlacion <- reservas %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba (estratificada)\n\nSeparamos 75% para entrenamiento y 25% para prueba. **Estratificamos** por `cancelo` para que ambas particiones conserven la misma proporción de clases. La prueba se reserva para el final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nreservas_split <- initial_split(reservas, prop = 0.75, strata = cancelo)\nreservas_entrenamiento <- reservas_split %>% training()\nreservas_prueba <- reservas_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(reservas_entrenamiento$cancelo) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4053333 0.5946667 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(reservas_prueba$cancelo) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4053333 0.5946667 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que ambos modelos vean la misma representación de los datos. El paso clave aquí es `step_dummy`, porque hay muchas variables categóricas que la regresión logística (y `rpart` en este flujo) necesitan en formato numérico.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se aprenden solo con el entrenamiento y se aplican igual a la prueba (esto evita fuga de información). El orden importa: se imputan los `NA` primero (los pasos siguientes no los toleran), se filtra colinealidad y se normaliza antes de crear *dummies*, y `step_zv` queda al final como red de seguridad.\n:::\n\nComo `pais_origen` (categórica) tiene faltantes, los imputamos por la **moda** (`step_impute_mode`), la categoría más frecuente. Los numéricos faltantes se imputan por la mediana.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Receta única comparable:\n#  1. Imputar numéricos (mediana) y nominales (moda; pais_origen tiene NAs).\n#  2. step_nzv: quitar casi-constantes.\n#  3. step_corr: filtrar colinealidad numérica.\n#  4. step_normalize: estandarizar numéricos (inocuo para el árbol, ordena la\n#     escala para la logística).\n#  5. step_dummy: codificar las muchas categóricas (tipo_habitacion, canal,\n#     regimen, temporada, forma_pago, pais_origen, etc.).\n#  6. step_zv: por seguridad.\nreceta_reservas <- recipe(cancelo ~ ., data = reservas_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nVerificamos cómo queda la base ya preprocesada: cada categoría se convirtió en una o varias columnas *dummy* (0/1).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_reservas %>%\n  prep(training = reservas_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,125\nColumns: 28\n$ dias_anticipacion          <dbl> -0.45769848, 0.15154324, -0.47800654, 0.801…\n$ num_noches                 <dbl> -0.68208290, 1.75392746, -1.03008438, -0.68…\n$ num_noches_finde           <dbl> -0.2631065, -0.2631065, -1.0630926, -1.0630…\n$ num_adultos                <dbl> -1.22959792, -0.02568351, -1.22959792, -0.0…\n$ num_ninos                  <dbl> -0.5871544, 0.7472874, -0.5871544, -0.58715…\n$ num_solicitudes_especiales <dbl> -0.6969154, 1.0590304, 1.0590304, -0.696915…\n$ num_estancias_previas      <dbl> -0.2180468, 0.7006898, -1.1367835, 3.456899…\n$ precio_total_mxn           <dbl> 0.86089954, 1.01452760, -0.64308044, 1.3028…\n$ descuento_aplicado_pct     <dbl> -0.9369235, -1.0822280, 2.6351457, -1.08222…\n$ cancelo                    <fct> no, no, no, no, no, no, no, no, no, no, no,…\n$ tipo_habitacion_estandar   <dbl> 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0…\n$ tipo_habitacion_junior     <dbl> 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0…\n$ tipo_habitacion_suite      <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0…\n$ canal_reserva_ota          <dbl> 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1…\n$ canal_reserva_telefono     <dbl> 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0…\n$ canal_reserva_web_propio   <dbl> 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…\n$ regimen_media_pension      <dbl> 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0…\n$ regimen_solo_habitacion    <dbl> 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1…\n$ regimen_todo_incluido      <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0…\n$ temporada_baja             <dbl> 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1…\n$ temporada_media            <dbl> 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0…\n$ forma_pago_deposito_50pct  <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0…\n$ forma_pago_en_hotel        <dbl> 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0…\n$ pais_origen_europa         <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0…\n$ pais_origen_mexico         <dbl> 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1…\n$ pais_origen_otro           <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ cliente_recurrente_si      <dbl> 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0…\n$ tiene_promocion_si         <dbl> 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nEl primer modelo es la **regresión logística**: no tiene hiperparámetros que ajustar. Modela el log-odds de cancelación como combinación lineal de los predictores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEl segundo es un **árbol de decisión**, donde ajustaremos la poda y la profundidad.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un árbol de decisión?\nUn **árbol** parte el espacio de predictores con reglas tipo \"si X > umbral, entonces...\", y predice la clase mayoritaria de cada hoja. Capta no linealidades e interacciones de forma automática, y su gran ventaja es que es **interpretable**: el diagrama resultante son reglas legibles. La desventaja es que un solo árbol es **inestable** (cambia mucho con pequeños cambios en los datos); por eso se ajustan `cost_complexity` (poda: castiga árboles grandes) y `tree_depth` (profundidad máxima) para regularizarlo.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Árbol de decisión (rpart). Tuneamos cost_complexity (poda) y tree_depth.\nmodelo_arbol <- decision_tree(\n    cost_complexity = tune(),\n    tree_depth = tune()\n  ) %>%\n  set_engine(\"rpart\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEmpaquetamos cada modelo con la misma receta en su `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_logistico <- workflow() %>%\n  add_recipe(receta_reservas) %>%\n  add_model(modelo_logistico)\n\nworkflow_arbol <- workflow() %>%\n  add_recipe(receta_reservas) %>%\n  add_model(modelo_arbol)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y validamos en el restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(reservas_entrenamiento, v = 5, strata = cancelo)\n```\n:::\n\n\nDefinimos las métricas de clasificación. El AUC será la métrica principal de comparación.\n\n::: {.callout-note collapse=\"true\"}\n## Matriz de confusión, sensibilidad, especificidad, ROC y AUC\n- **Matriz de confusión:** tabla que cruza la clase real con la predicha (verdaderos/falsos positivos y negativos).\n- **Sensibilidad (recall):** de los positivos reales, cuántos detecta el modelo.\n- **Especificidad:** de los negativos reales, cuántos clasifica bien.\n- **Curva ROC:** traza sensibilidad vs. (1 − especificidad) variando el umbral de decisión.\n- **AUC:** área bajo la curva ROC; resume la discriminación (0.5 = azar, 1 = perfecto) sin depender de un umbral fijo. Es la métrica principal cuando las clases están balanceadas.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_clasificacion <- metric_set(roc_auc, accuracy, sensitivity,\n                                     yardstick::spec)\n```\n:::\n\n\nLa logística no se tunea: estimamos su desempeño en CV con `fit_resamples()`.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (la regresión logística), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el árbol, con `cost_complexity` y `tree_depth`), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_logistico <- workflow_logistico %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_clasificacion)\n\ncollect_metrics(cv_logistico)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric     |.estimator |      mean|  n|   std_err|.config         |\n|:-----------|:----------|---------:|--:|---------:|:---------------|\n|accuracy    |binary     | 0.6800093|  5| 0.0079668|pre0_mod0_post0 |\n|roc_auc     |binary     | 0.7243481|  5| 0.0121876|pre0_mod0_post0 |\n|sensitivity |binary     | 0.5284998|  5| 0.0115711|pre0_mod0_post0 |\n|spec        |binary     | 0.7832791|  5| 0.0126229|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara el árbol definimos una grilla que combina valores de `cost_complexity` y `tree_depth`, y corremos la validación cruzada en cada combinación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_arbol <- grid_regular(cost_complexity(),\n                             tree_depth(),\n                             levels = 4)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_arbol <- workflow_arbol %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_arbol,\n            metrics = metricas_clasificacion)\n```\n:::\n\n\nLa gráfica muestra el AUC promedio en validación cruzada según la profundidad del árbol, con una línea por cada nivel de `cost_complexity`. Nos ayuda a ver qué tan profundo conviene crecer el árbol antes de que empiece a sobreajustar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_arbol %>%\n  collect_metrics() %>%\n  filter(.metric == \"roc_auc\") %>%\n  ggplot(aes(x = tree_depth, y = mean,\n             color = factor(round(cost_complexity, 5)))) +\n  geom_line() +\n  geom_point(size = 2) +\n  labs(title = \"AUC en validación cruzada — árbol de decisión\",\n       x = \"Profundidad del árbol\", y = \"AUC promedio\",\n       color = \"cost_complexity\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n\nSeleccionamos la combinación de hiperparámetros con mayor AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_arbol <- tuning_arbol %>% select_best(metric = \"roc_auc\")\nmejor_arbol\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cost_complexity| tree_depth|.config          |\n|---------------:|----------:|:----------------|\n|               0|          5|pre0_mod02_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa logística ya está lista; al árbol le inyectamos los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_arbol_final <- workflow_arbol %>%\n  finalize_workflow(mejor_arbol)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_logistico <- workflow_logistico %>%\n  last_fit(split = reservas_split, metrics = metricas_clasificacion)\n\najuste_arbol <- workflow_arbol_final %>%\n  last_fit(split = reservas_split, metrics = metricas_clasificacion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de ambos modelos en la prueba en una sola tabla, ordenada por AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_logistico) %>% mutate(modelo = \"Regresión logística\"),\n    collect_metrics(ajuste_arbol) %>% mutate(modelo = \"Árbol de decisión\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(desc(roc_auc))\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              |  accuracy| sensitivity|      spec|   roc_auc|\n|:-------------------|---------:|-----------:|---------:|---------:|\n|Regresión logística | 0.6426667|   0.5000000| 0.7399103| 0.6991680|\n|Árbol de decisión   | 0.6053333|   0.5131579| 0.6681614| 0.6421407|\n\n</div>\n:::\n:::\n\n\nLas **curvas ROC sobrepuestas** comparan visualmente la discriminación: entre más se acerque una curva a la esquina superior izquierda, mejor separa las reservas que se cancelan de las que no.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_logistico <- collect_predictions(ajuste_logistico) %>%\n  mutate(modelo = \"Regresión logística\")\npreds_arbol <- collect_predictions(ajuste_arbol) %>%\n  mutate(modelo = \"Árbol de decisión\")\n\npreds_ambos <- bind_rows(preds_logistico, preds_arbol)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  group_by(modelo) %>%\n  roc_curve(truth = cancelo, .pred_si) %>%\n  autoplot() +\n  labs(title = \"Curvas ROC en la base de prueba\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\nLas **matrices de confusión** muestran en qué se equivoca cada modelo (falsos positivos vs. falsos negativos), información que el AUC resume pero no detalla. Para el hotel, un falso negativo (no anticipar una cancelación real) y un falso positivo (alertar una cancelación que no ocurre) tienen costos distintos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_logistico, truth = cancelo, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Regresión logística\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_arbol, truth = cancelo, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Árbol de decisión\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\nLa gran ventaja del árbol es su **interpretabilidad**: el diagrama siguiente muestra las reglas que aprendió. Cada nodo es una pregunta sobre una variable; siguiendo las ramas hasta una hoja se obtiene la predicción. Estas reglas legibles son muy fáciles de comunicar a un área operativa (\"las reservas con mucha anticipación por canal OTA y sin depósito tienden a cancelarse\"), algo que la logística, basada en coeficientes, comunica con menos transparencia.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ventaja del árbol: es interpretable. Visualizamos las reglas aprendidas.\najuste_arbol %>%\n  extract_fit_engine() %>%\n  rpart.plot::rpart.plot(roundint = FALSE, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-30-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\nComo las clases están razonablemente balanceadas, decidimos por el **AUC en la base de prueba** (mayor es mejor). Ordenamos la tabla y calculamos la diferencia de AUC entre el ganador y el segundo lugar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final <- metricas_comparacion %>%\n  mutate(across(where(is.numeric), ~ round(., 3))) %>%\n  arrange(desc(roc_auc))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_auc <- round(ganador$roc_auc - perdedor$roc_auc, 3)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              | accuracy| sensitivity|  spec| roc_auc|\n|:-------------------|--------:|-----------:|-----:|-------:|\n|Regresión logística |    0.643|       0.500| 0.740|   0.699|\n|Árbol de decisión   |    0.605|       0.513| 0.668|   0.642|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión logística.** Obtiene el mayor AUC en la base de prueba (0.699), frente a 0.642 del otro modelo (diferencia de 0.057).\n\n> La ventaja de **Regresión logística** es clara (0.057 de AUC), por lo que es la elección recomendada para este problema.\n\nComo las clases están casi balanceadas, el *accuracy* también es informativo aquí; en problemas desbalanceados habría que mirar recall y precision en su lugar. Y aunque el AUC favorezca a uno u otro modelo, el árbol conserva una ventaja cualitativa: su diagrama de reglas facilita explicar y operar la política de retención o sobreventa.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}