{
  "hash": "80a788f062c8532a5420976a34188966",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión: consumo eléctrico residencial\"\nsubtitle: \"EJERCICIO DE REGRESIÓN — Regresión lineal vs. árbol de regresión\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir el consumo eléctrico mensual de un hogar (`consumo_kwh`) a partir de sus características físicas y de uso. Compararemos dos modelos sobre el mismo flujo de trabajo: una **regresión lineal** (modelo base, interpretable) y un **árbol de regresión** (capta relaciones no lineales y umbrales). Recorreremos el flujo completo de `tidymodels`: partición de los datos, receta de preprocesamiento, `workflow()`, validación cruzada, ajuste de hiperparámetros y una evaluación honesta con `last_fit()`. Al final daremos un **veredicto claro** sobre cuál modelo conviene.\n\n## 1. Cargar librerías\n\nAgrupamos todas las librerías al inicio (buena práctica de reproducibilidad). `tidyverse` da el lenguaje de manipulación de datos; `tidymodels` es el marco de modelado; `rpart` es el motor que ajusta el árbol de regresión; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(rpart)\n```\n:::\n\n\n`tidymodels_prefer()` resuelve los conflictos de nombres a favor de tidymodels (por ejemplo, que `spec()` sea la de yardstick y no la de otro paquete).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nLeemos el CSV y removemos `hogar_id`: es un identificador único por fila, no aporta poder predictivo y, si lo dejáramos, solo metería ruido. Las dos variables de texto (`aislamiento`, `tarifa_horaria`) las dejamos como están; la receta las convertirá en variables *dummy* más adelante.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenergia <- read_csv(\"datos.csv\") %>%\n  select(-hogar_id)\n```\n:::\n\n\n`glimpse()` nos da un vistazo rápido a tipos y valores de cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(energia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 420\nColumns: 8\n$ consumo_kwh      <dbl> 458.3364, 267.0903, 383.4330, 355.8243, 481.6234, 374…\n$ temp_promedio_c  <dbl> 27.60295, 19.60155, 25.69619, 24.57626, 21.66680, 12.…\n$ grados_calor     <dbl> 5.6029454, 0.0000000, 3.6961906, 2.5762561, 0.0000000…\n$ metros_cuadrados <dbl> 127.71559, 98.69214, 152.72687, 58.73435, 89.31725, 1…\n$ ocupantes        <dbl> 4, 1, 2, 3, 5, 3, 3, 2, 4, 5, 1, 3, 4, 6, 2, 2, 2, 1,…\n$ antiguedad_anios <dbl> 41, 17, 24, 27, 34, 9, 25, 26, 7, 7, 40, 34, 16, 27, …\n$ aislamiento      <chr> \"medio\", \"basico\", \"medio\", \"medio\", \"basico\", \"basic…\n$ tarifa_horaria   <chr> \"fija\", \"fija\", \"fija\", \"variable\", \"fija\", \"fija\", \"…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nAntes de modelar conviene entender la variable objetivo y las relaciones entre predictores. Tres revisiones mínimas: la **distribución de la objetivo** (¿hay asimetría o valores extremos?), los **datos faltantes** (¿qué tendremos que imputar?) y la **colinealidad** (¿hay predictores que miden casi lo mismo?).\n\nPrimero, el histograma del consumo. Buscamos si la distribución es aproximadamente simétrica (cómodo para la regresión lineal) o muy sesgada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenergia %>%\n  ggplot(aes(x = consumo_kwh)) +\n  geom_histogram(bins = 30, fill = \"#1e4c7d\", color = \"white\") +\n  labs(title = \"Distribución del consumo eléctrico mensual\",\n       x = \"Consumo (kWh)\", y = \"Frecuencia\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n`summary()` resume cada variable y, de paso, nos dice cuántos `NA` tiene cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(energia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  consumo_kwh    temp_promedio_c  grados_calor    metros_cuadrados\n Min.   :137.3   Min.   :12.27   Min.   : 0.000   Min.   : 33.50  \n 1st Qu.:313.0   1st Qu.:21.62   1st Qu.: 0.000   1st Qu.: 72.36  \n Median :368.8   Median :25.09   Median : 3.087   Median : 93.72  \n Mean   :373.2   Mean   :25.10   Mean   : 3.897   Mean   : 99.32  \n 3rd Qu.:440.0   3rd Qu.:28.11   3rd Qu.: 6.113   3rd Qu.:116.34  \n Max.   :655.8   Max.   :38.19   Max.   :16.194   Max.   :304.16  \n   ocupantes     antiguedad_anios aislamiento        tarifa_horaria    \n Min.   :1.000   Min.   : 0.00    Length:420         Length:420        \n 1st Qu.:2.000   1st Qu.:15.00    Class :character   Class :character  \n Median :3.000   Median :24.00    Mode  :character   Mode  :character  \n Mean   :3.114   Mean   :23.79                                         \n 3rd Qu.:4.000   3rd Qu.:33.00                                         \n Max.   :6.000   Max.   :58.00                                         \n```\n\n\n:::\n:::\n\n\nContamos los `NA` por columna de forma explícita: esto guía qué pasos de imputación necesitará la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenergia %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable         | n_na|\n|:----------------|----:|\n|consumo_kwh      |    0|\n|temp_promedio_c  |    0|\n|grados_calor     |    0|\n|metros_cuadrados |    0|\n|ocupantes        |    0|\n|antiguedad_anios |    0|\n|aislamiento      |    0|\n|tarifa_horaria   |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación nos deja ver colinealidad entre predictores numéricos (por ejemplo, `temp_promedio_c` y `grados_calor` suelen moverse juntas). Si dos variables miden casi lo mismo, la regresión lineal sufre (infla la varianza de los coeficientes); por eso más adelante filtraremos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatriz_correlacion <- energia %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba\n\nDividimos los datos en **entrenamiento** (75%) y **prueba** (25%). La base de prueba se \"guarda en una caja fuerte\": no la tocamos hasta el final, para obtener una estimación honesta del desempeño en datos nuevos. Estratificamos por la objetivo para que ambas particiones cubran rangos de consumo parecidos (en regresión, `initial_split` estratifica por cuantiles).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nenergia_split <- initial_split(energia, prop = 0.75, strata = consumo_kwh)\nenergia_entrenamiento <- energia_split %>% training()\nenergia_prueba <- energia_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(entrenamiento = nrow(energia_entrenamiento),\n  prueba = nrow(energia_prueba))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nentrenamiento        prueba \n          312           108 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que los dos modelos sean comparables: ambos verán exactamente la misma representación de los datos.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se *aprenden* solo con el entrenamiento y luego se aplican igual a la prueba (esto evita fuga de información). El orden importa: imputamos los `NA` **primero**, porque pasos como `step_corr` o `step_normalize` no toleran faltantes; normalizamos antes de crear *dummies* para que estas queden en 0/1; y dejamos `step_zv` al final como red de seguridad.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_energia <- recipe(consumo_kwh ~ ., data = energia_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%   # imputar NAs numéricos\n  step_impute_mode(all_nominal_predictors()) %>%      # imputar NAs categóricos\n  step_nzv(all_predictors()) %>%                      # quitar casi-constantes\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%  # colinealidad\n  step_normalize(all_numeric_predictors()) %>%        # estandarizar\n  step_dummy(all_nominal_predictors()) %>%            # codificar categóricas\n  step_zv(all_predictors())                           # red de seguridad\n```\n:::\n\n\nConviene \"hornear\" la receta una vez para ver cómo quedan las variables tras el preprocesamiento (solo es inspección; el `workflow` lo hará por nosotros después).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_energia %>%\n  prep(training = energia_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 312\nColumns: 8\n$ grados_calor            <dbl> -1.04182867, -0.79042605, -1.04182867, 1.51040…\n$ metros_cuadrados        <dbl> 0.02828771, -0.58884675, 0.88733487, -1.573441…\n$ ocupantes               <dbl> -1.51667628, -1.51667628, -0.79642818, -0.7964…\n$ antiguedad_anios        <dbl> -0.49157422, 1.29181132, -0.10388171, -0.72418…\n$ consumo_kwh             <dbl> 267.0903, 274.0353, 305.4181, 261.7358, 298.06…\n$ aislamiento_basico      <dbl> 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0…\n$ aislamiento_medio       <dbl> 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1…\n$ tarifa_horaria_variable <dbl> 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nDefinimos los dos modelos con `parsnip`. El primero es la **regresión lineal**: no tiene hiperparámetros que ajustar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_lineal <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nEl segundo es el **árbol de regresión**, donde sí ajustaremos dos hiperparámetros.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un árbol de regresión?\nUn **árbol de regresión** parte el espacio de predictores con reglas tipo \"si `metros_cuadrados` > X y `aislamiento` = bueno, entonces...\", y predice el promedio de cada hoja. Capta no linealidades y umbrales que la regresión lineal no ve, pero un solo árbol es **inestable** (cambia mucho con pequeñas variaciones de los datos). Ajustamos `cost_complexity` (poda: penaliza árboles grandes) y `tree_depth` (profundidad máxima) para regularizarlo. `tune()` marca esos valores como \"a determinar por validación cruzada\".\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_arbol <- decision_tree(\n    cost_complexity = tune(),\n    tree_depth = tune()\n  ) %>%\n  set_engine(\"rpart\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nCada modelo se empaqueta con la **misma** receta en su propio `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos sin que tengamos que recordarlo. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_lineal <- workflow() %>%\n  add_recipe(receta_energia) %>%\n  add_model(modelo_lineal)\n\nworkflow_arbol <- workflow() %>%\n  add_recipe(receta_energia) %>%\n  add_model(modelo_arbol)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\nPara comparar los modelos y elegir los hiperparámetros del árbol **sin tocar la prueba**, usamos validación cruzada sobre el entrenamiento.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y evaluamos en el fold restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(energia_entrenamiento, v = 5, strata = consumo_kwh)\n```\n:::\n\n\nDefinimos las métricas de regresión que vigilaremos.\n\n::: {.callout-note collapse=\"true\"}\n## RMSE, MAE y R²\n- **RMSE** (raíz del error cuadrático medio): error típico en las unidades de la objetivo; penaliza más los errores grandes. Es la métrica de decisión.\n- **MAE** (error absoluto medio): error típico, más robusto a valores extremos.\n- **R²**: proporción de la variación de la objetivo que el modelo explica (1 = perfecto; 0 = no mejor que predecir la media).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_regresion <- metric_set(rmse, rsq, mae)\n```\n:::\n\n\nLa regresión lineal **no se tunea**; estimamos su desempeño en CV con `fit_resamples()`. Esto la pone en igualdad de condiciones que el árbol.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (regresión lineal), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el árbol), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_lineal <- workflow_lineal %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_regresion)\n\ncollect_metrics(cv_lineal)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric |.estimator |       mean|  n|   std_err|.config         |\n|:-------|:----------|----------:|--:|---------:|:---------------|\n|mae     |standard   | 37.2224572|  5| 1.5138717|pre0_mod0_post0 |\n|rmse    |standard   | 46.5809653|  5| 1.8709439|pre0_mod0_post0 |\n|rsq     |standard   |  0.7367461|  5| 0.0225192|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara el árbol construimos una grilla de hiperparámetros: combinaciones de `cost_complexity` y `tree_depth` (`levels = 4` da 4 × 4 = 16 candidatos).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_arbol <- grid_regular(cost_complexity(),\n                             tree_depth(),\n                             levels = 4)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_arbol <- workflow_arbol %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_arbol,\n            metrics = metricas_regresion)\n```\n:::\n\n\nLa siguiente gráfica resume el tuning: muestra el RMSE de validación cruzada según la profundidad del árbol, con una línea por nivel de poda. Buscamos la combinación con menor RMSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_arbol %>%\n  collect_metrics() %>%\n  filter(.metric == \"rmse\") %>%\n  ggplot(aes(x = tree_depth, y = mean,\n             color = factor(round(cost_complexity, 5)))) +\n  geom_line() +\n  geom_point(size = 2) +\n  labs(title = \"RMSE en validación cruzada — árbol de regresión\",\n       x = \"Profundidad del árbol\", y = \"RMSE promedio\",\n       color = \"cost_complexity\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-22-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_arbol <- tuning_arbol %>% select_best(metric = \"rmse\")\nmejor_arbol\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| cost_complexity| tree_depth|.config          |\n|---------------:|----------:|:----------------|\n|               0|         10|pre0_mod03_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa regresión lineal ya está lista. Al árbol le **inyectamos** los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_arbol_final <- workflow_arbol %>%\n  finalize_workflow(mejor_arbol)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_lineal <- workflow_lineal %>%\n  last_fit(split = energia_split, metrics = metricas_regresion)\n\najuste_arbol <- workflow_arbol_final %>%\n  last_fit(split = energia_split, metrics = metricas_regresion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de **ambos** modelos en la base de prueba en una sola tabla. Esta es la comparación que nos interesa: el desempeño en datos no vistos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_lineal) %>% mutate(modelo = \"Regresión lineal\"),\n    collect_metrics(ajuste_arbol) %>% mutate(modelo = \"Árbol de regresión\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(rmse)\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo             |     rmse|       rsq|      mae|\n|:------------------|--------:|---------:|--------:|\n|Regresión lineal   | 43.84808| 0.7942473| 35.34263|\n|Árbol de regresión | 65.14123| 0.5733230| 52.74761|\n\n</div>\n:::\n:::\n\n\nPara visualizar la calidad de cada modelo, graficamos los valores reales contra los predichos. La diagonal roja es la predicción perfecta: entre más pegados los puntos a la línea, mejor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_lineal <- collect_predictions(ajuste_lineal) %>%\n  mutate(modelo = \"Regresión lineal\")\npreds_arbol <- collect_predictions(ajuste_arbol) %>%\n  mutate(modelo = \"Árbol de regresión\")\n\npreds_ambos <- bind_rows(preds_lineal, preds_arbol)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  ggplot(aes(x = consumo_kwh, y = .pred)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_abline(color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Valores reales vs. predichos (base de prueba)\",\n       x = \"Consumo real (kWh)\", y = \"Consumo predicho (kWh)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\nEl gráfico de residuos (real − predicho) contra el valor predicho ayuda a detectar sesgos: buscamos una nube sin patrón alrededor del cero. Un embudo o una curva indicarían que el modelo se equivoca sistemáticamente en algún rango.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  mutate(residuo = consumo_kwh - .pred) %>%\n  ggplot(aes(x = .pred, y = residuo)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_hline(yintercept = 0, color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Residuos vs. valores predichos\",\n       x = \"Consumo predicho (kWh)\", y = \"Residuo (real − predicho)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordenamos por RMSE (menor es mejor) y medimos la diferencia relativa entre\n# el mejor y el segundo, para juzgar si la ventaja es relevante o marginal.\ntabla_final <- metricas_comparacion %>%\n  arrange(rmse) %>%\n  mutate(rmse = round(rmse, 2),\n         rsq = round(rsq, 3),\n         mae = round(mae, 2))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_rel_pct <- round(100 * (perdedor$rmse - ganador$rmse) / perdedor$rmse, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tabla comparativa final (ordenada del mejor al peor por RMSE)\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo             |  rmse|   rsq|   mae|\n|:------------------|-----:|-----:|-----:|\n|Regresión lineal   | 43.85| 0.794| 35.34|\n|Árbol de regresión | 65.14| 0.573| 52.75|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión lineal.** Obtiene el menor RMSE en la base de prueba (43.85 kWh) con un R² de 0.794, frente a 65.14 kWh del árbol de regresión. Su RMSE es **32.7% menor**.\n\n> La ventaja de **Regresión lineal** es relevante (32.7% en RMSE), por lo que es la elección clara para este problema.\n\nRecuerda que la regresión lineal es la más fácil de interpretar (un coeficiente por variable), mientras que el árbol capta umbrales y no linealidades a costa de mayor inestabilidad; el tuning de `cost_complexity` y `tree_depth` lo regulariza.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}