{
  "hash": "4ec4f5ab87ee8a97c9d58e1394ec0741",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clasificación: deserción estudiantil\"\nsubtitle: \"EJERCICIO DE CLASIFICACIÓN — Regresión logística vs. KNN\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir si un estudiante desertará (`deserto`: si/no) durante el primer año, para canalizar a tiempo a programas de tutoría. Compararemos dos clasificadores sobre un mismo flujo de trabajo: una **regresión logística** (lineal, interpretable) y **KNN** (k-vecinos más cercanos, basado en distancias). El conjunto de datos mezcla variables numéricas (promedios, horas de estudio) y categóricas (carrera, beca), por lo que la receta incluye la creación de variables *dummy*. Recorremos el flujo completo: partición, receta, `workflow()`, validación cruzada, tuning del número de vecinos y evaluación honesta con `last_fit()`, y cerramos con una recomendación clara.\n\n## 1. Cargar librerías\n\nCargamos todo al inicio. `kknn` es el motor que `parsnip` usa por detrás para KNN; `corrplot` dibuja la matriz de correlación y `readxl` lee el archivo de Excel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(kknn)\nlibrary(readxl)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nLos datos vienen en Excel y no traen columna identificadora. Convertimos la objetivo a `factor` fijando `\"si\"` (desertó) como **primer nivel**: `yardstick` toma el primer nivel como el evento de interés, de modo que la sensibilidad, el AUC y demás métricas se calculen sobre \"deserción = si\", que es justo lo que queremos detectar a tiempo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Los datos vienen en Excel; no hay columna identificadora. Convertimos la\n# objetivo a factor con \"si\" (desertó) como PRIMER nivel, que es el evento de\n# interés para detección temprana.\nestudiantes <- read_excel(\"estudiantes.xlsx\") %>%\n  mutate(deserto = factor(deserto, levels = c(\"si\", \"no\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(estudiantes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,000\nColumns: 15\n$ promedio_prepa         <dbl> 8.61, 7.65, 8.38, 8.25, 7.90, 6.79, 7.86, 7.69,…\n$ examen_admision        <dbl> 1266, 1135, NA, 948, 1159, 907, 1098, 1018, 924…\n$ horas_estudio_semanal  <dbl> 15.2, 15.0, 14.5, 9.0, 10.3, 17.6, 12.1, 15.3, …\n$ horas_lectura_semanal  <dbl> 7.7, 10.0, 12.8, 5.9, 7.3, 12.7, 11.7, 4.7, 9.2…\n$ asistencia_pct         <dbl> 100.0, 80.8, 100.0, 64.1, 74.9, 91.8, 94.3, 89.…\n$ reprobaciones          <dbl> 2, 1, 2, 0, 2, 3, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0,…\n$ edad                   <dbl> 19, 21, 18, 24, 21, 22, 21, 19, 18, 21, 21, 22,…\n$ ingreso_familiar_miles <dbl> 31.7, 22.9, 67.0, 60.3, 26.5, 32.7, 39.0, 21.2,…\n$ distancia_campus_km    <dbl> 18.1, 5.2, 31.4, 24.7, 8.4, 15.7, 19.3, 0.9, 9.…\n$ carrera                <chr> \"Ingenieria\", \"Ingenieria\", \"Salud\", \"Salud\", \"…\n$ tipo_beca              <chr> \"parcial\", \"parcial\", \"parcial\", \"ninguna\", \"co…\n$ trabaja                <chr> \"no\", \"si\", \"no\", \"no\", \"no\", \"no\", \"si\", \"no\",…\n$ vive_con_familia       <chr> \"si\", \"si\", \"no\", \"si\", \"si\", \"si\", \"si\", \"si\",…\n$ inscrito_sistema       <chr> \"si\", \"si\", \"si\", \"si\", \"si\", \"si\", \"si\", \"si\",…\n$ deserto                <fct> no, no, no, si, si, si, no, si, si, no, si, si,…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nTres revisiones mínimas antes de modelar: el **balance de clases**, los **datos faltantes** y la **colinealidad** entre variables numéricas.\n\nEl balance importa porque, si una clase fuera muy rara, el *accuracy* dejaría de ser confiable (predecir siempre la mayoría daría un accuracy alto pero inútil). En este conjunto la deserción ronda el 37%, así que las clases están razonablemente balanceadas y podemos confiar en métricas como el AUC y el accuracy sin recurrir a técnicas de rebalanceo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestudiantes %>%\n  group_by(deserto) %>%\n  count() %>%\n  ungroup() %>%\n  mutate(porcentaje = 100 * (n / sum(n)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|deserto |   n| porcentaje|\n|:-------|---:|----------:|\n|si      | 366|       36.6|\n|no      | 634|       63.4|\n\n</div>\n:::\n:::\n\n\nContamos los `NA`: esto guía la imputación que haremos en la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestudiantes %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable               | n_na|\n|:----------------------|----:|\n|ingreso_familiar_miles |   50|\n|examen_admision        |   30|\n|promedio_prepa         |    0|\n|horas_estudio_semanal  |    0|\n|horas_lectura_semanal  |    0|\n|asistencia_pct         |    0|\n|reprobaciones          |    0|\n|edad                   |    0|\n|distancia_campus_km    |    0|\n|carrera                |    0|\n|tipo_beca              |    0|\n|trabaja                |    0|\n|vive_con_familia       |    0|\n|inscrito_sistema       |    0|\n|deserto                |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación revela colinealidad entre variables numéricas (esperamos relación entre horas de estudio y horas de lectura). En KNN, dos variables redundantes harían que esa información pese doble en el cálculo de distancias; por eso luego las filtramos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colinealidad numérica: esperamos relación entre horas de estudio y de lectura.\nmatriz_correlacion <- estudiantes %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba (estratificada)\n\nSeparamos 75% para entrenamiento y 25% para prueba. **Estratificamos** por `deserto` para que ambas particiones conserven la misma proporción de clases. La prueba se reserva para el final y no se toca durante el modelado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nestudiantes_split <- initial_split(estudiantes, prop = 0.75, strata = deserto)\nestudiantes_entrenamiento <- estudiantes_split %>% training()\nestudiantes_prueba <- estudiantes_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(estudiantes_entrenamiento$deserto) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.3658211 0.6341789 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(estudiantes_prueba$deserto) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.3665339 0.6334661 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que ambos modelos vean exactamente la misma representación de los datos y la comparación sea justa.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se aprenden solo con el entrenamiento y se aplican igual a la prueba (esto evita fuga de información). El orden importa: se imputan los `NA` primero (los pasos siguientes no los toleran), se quitan las casi-constantes, se filtra colinealidad y se **normaliza** antes de crear *dummies*, y `step_zv` queda al final como red de seguridad.\n:::\n\nA diferencia de un problema con solo variables numéricas, aquí tenemos categóricas (carrera, beca, etc.), así que añadimos `step_dummy` para convertirlas en columnas indicadoras. También usamos `step_nzv`, que elimina predictores casi constantes (como `inscrito_sistema`, que toma casi siempre el mismo valor y no aporta información para discriminar).\n\n::: {.callout-note collapse=\"true\"}\n## ¿Por qué normalizar para KNN?\nKNN clasifica por **distancia** entre observaciones. Sin estandarizar, una variable de gran escala (por ejemplo, horas de estudio acumuladas) aplastaría a otras de escala pequeña (número de materias) en el cálculo de distancias. `step_normalize` deja todas las variables numéricas en media 0 y desviación 1, de modo que todas pesen de forma comparable.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Una sola receta comparable. El orden importa:\n#  1. Imputar numéricos (mediana) y nominales (moda).\n#  2. step_nzv: quitar casi-constantes (p. ej. inscrito_sistema).\n#  3. step_corr: filtrar colinealidad numérica.\n#  4. step_normalize: estandarizar numéricos (CRÍTICO para KNN).\n#  5. step_dummy: codificar carrera, tipo_beca, trabaja, vive_con_familia.\n#  6. step_zv: por seguridad.\nreceta_estudiantes <- recipe(deserto ~ ., data = estudiantes_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nAplicamos la receta al entrenamiento (`prep` + `bake`) solo para inspeccionar cómo quedan los datos preprocesados: numéricos estandarizados y categóricas convertidas en columnas *dummy*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_estudiantes %>%\n  prep(training = estudiantes_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 749\nColumns: 18\n$ promedio_prepa         <dbl> -1.10635993, 0.14932127, -0.74513657, -0.211902…\n$ examen_admision        <dbl> 0.959103544, 0.011888559, 0.696579541, -1.17656…\n$ horas_estudio_semanal  <dbl> 0.17965222, 0.09680558, -0.30085829, -0.2511503…\n$ horas_lectura_semanal  <dbl> 0.28532369, 1.04836992, 0.74860176, -0.58672914…\n$ asistencia_pct         <dbl> -0.262473951, 1.370555986, 0.885750224, -0.4921…\n$ reprobaciones          <dbl> -0.1921057, 0.7483335, -0.1921057, -1.1325450, …\n$ edad                   <dbl> 0.3494946, -1.2179993, 0.3494946, -0.1730033, -…\n$ ingreso_familiar_miles <dbl> -0.5761503, 1.4787635, 0.1740563, -0.4969359, -…\n$ distancia_campus_km    <dbl> -0.5296846, 2.1437785, 0.9090875, 0.2254157, -0…\n$ deserto                <fct> no, no, no, no, no, no, no, no, no, no, no, no,…\n$ carrera_Humanidades    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,…\n$ carrera_Ingenieria     <dbl> 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ carrera_Negocios       <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,…\n$ carrera_Salud          <dbl> 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ tipo_beca_ninguna      <dbl> 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,…\n$ tipo_beca_parcial      <dbl> 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,…\n$ trabaja_si             <dbl> 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,…\n$ vive_con_familia_si    <dbl> 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nEl primer modelo es la **regresión logística**: no tiene hiperparámetros que ajustar. Modela el log-odds de deserción como combinación lineal de los predictores, lo que la hace fácil de interpretar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEl segundo es **KNN**, donde ajustaremos el número de vecinos `k`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es KNN y qué controla k?\n**KNN** clasifica una observación nueva según la clase mayoritaria de sus `k` vecinos más cercanos en el espacio de predictores. `k` gobierna el equilibrio sesgo-varianza: un `k` muy chico sobreajusta al ruido (frontera muy flexible), uno muy grande subajusta (frontera demasiado suave). Usamos `weight_func = \"rectangular\"` (voto no ponderado) para que ese equilibrio se vea con claridad y el `k` óptimo caiga en un valor intermedio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_knn <- nearest_neighbor(\n    neighbors = tune(),\n    weight_func = \"rectangular\"\n  ) %>%\n  set_engine(\"kknn\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEmpaquetamos cada modelo con la misma receta en su `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_logistico <- workflow() %>%\n  add_recipe(receta_estudiantes) %>%\n  add_model(modelo_logistico)\n\nworkflow_knn <- workflow() %>%\n  add_recipe(receta_estudiantes) %>%\n  add_model(modelo_knn)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\nConstruimos los folds para la validación cruzada, estratificados por la objetivo para que cada fold conserve la proporción de deserción.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y validamos en el restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final. Sirve tanto para comparar modelos como para elegir hiperparámetros.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(estudiantes_entrenamiento, v = 5, strata = deserto)\n```\n:::\n\n\nDefinimos el conjunto de métricas de clasificación que reportaremos.\n\n::: {.callout-note collapse=\"true\"}\n## Matriz de confusión, sensibilidad, especificidad, ROC y AUC\n- **Matriz de confusión:** tabla que cruza la clase real con la predicha (verdaderos/falsos positivos y negativos).\n- **Sensibilidad (recall):** de los positivos reales, cuántos detecta el modelo.\n- **Especificidad:** de los negativos reales, cuántos clasifica bien.\n- **Curva ROC:** traza sensibilidad vs. (1 − especificidad) variando el umbral de decisión.\n- **AUC:** área bajo la curva ROC; resume la discriminación (0.5 = azar, 1 = perfecto) sin depender de un umbral fijo. Es la métrica principal cuando las clases están balanceadas, como aquí.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_clasificacion <- metric_set(roc_auc, accuracy, sensitivity,\n                                     yardstick::spec)\n```\n:::\n\n\nLa logística no se tunea: estimamos su desempeño en validación cruzada con `fit_resamples()`.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (la regresión logística), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el `k` de KNN), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_logistico <- workflow_logistico %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_clasificacion)\n\ncollect_metrics(cv_logistico)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric     |.estimator |      mean|  n|   std_err|.config         |\n|:-----------|:----------|---------:|--:|---------:|:---------------|\n|accuracy    |binary     | 0.7556421|  5| 0.0100092|pre0_mod0_post0 |\n|roc_auc     |binary     | 0.8353698|  5| 0.0098286|pre0_mod0_post0 |\n|sensitivity |binary     | 0.6165657|  5| 0.0495975|pre0_mod0_post0 |\n|spec        |binary     | 0.8357895|  5| 0.0245965|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara KNN definimos una grilla de valores de `k` y corremos la validación cruzada en cada uno.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_k <- grid_regular(neighbors(range = c(1, 101)), levels = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_knn <- workflow_knn %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_k,\n            metrics = metricas_clasificacion)\n```\n:::\n\n\nLa gráfica de AUC promedio vs. `k` (con barras de error de ±1 error estándar) muestra el equilibrio sesgo-varianza: el AUC sube desde un `k` muy chico hacia un `k` intermedio y vuelve a bajar con `k` muy grande. Elegimos el `k` que maximiza el AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_knn %>%\n  collect_metrics() %>%\n  filter(.metric == \"roc_auc\") %>%\n  ggplot(aes(x = neighbors, y = mean)) +\n  geom_line() +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err),\n                width = 1.5) +\n  labs(title = \"AUC promedio por valor de k (validación cruzada 5-fold)\",\n       x = \"k (número de vecinos)\", y = \"AUC promedio\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_k <- tuning_knn %>% select_best(metric = \"roc_auc\")\nmejor_k\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| neighbors|.config          |\n|---------:|:----------------|\n|       101|pre0_mod12_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa logística ya está lista; al KNN le inyectamos el `k` ganador con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_knn_final <- workflow_knn %>%\n  finalize_workflow(mejor_k)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_logistico <- workflow_logistico %>%\n  last_fit(split = estudiantes_split, metrics = metricas_clasificacion)\n\najuste_knn <- workflow_knn_final %>%\n  last_fit(split = estudiantes_split, metrics = metricas_clasificacion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de ambos modelos en la prueba en una sola tabla, ordenada por AUC de mayor a menor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_logistico) %>% mutate(modelo = \"Regresión logística\"),\n    collect_metrics(ajuste_knn) %>% mutate(modelo = \"KNN\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(desc(roc_auc))\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              |  accuracy| sensitivity|      spec|   roc_auc|\n|:-------------------|---------:|-----------:|---------:|---------:|\n|Regresión logística | 0.7968127|   0.6413043| 0.8867925| 0.8466639|\n|KNN                 | 0.6494024|   0.0434783| 1.0000000| 0.7818909|\n\n</div>\n:::\n:::\n\n\nReunimos las predicciones de ambos modelos sobre la prueba para graficarlas juntas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_logistico <- collect_predictions(ajuste_logistico) %>%\n  mutate(modelo = \"Regresión logística\")\npreds_knn <- collect_predictions(ajuste_knn) %>%\n  mutate(modelo = \"KNN\")\n\npreds_ambos <- bind_rows(preds_logistico, preds_knn)\n```\n:::\n\n\nLas **curvas ROC sobrepuestas** comparan visualmente la discriminación de ambos modelos: entre más se acerque una curva a la esquina superior izquierda, mejor separa a quienes desertan de quienes no.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  group_by(modelo) %>%\n  roc_curve(truth = deserto, .pred_si) %>%\n  autoplot() +\n  labs(title = \"Curvas ROC en la base de prueba\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\nLas **matrices de confusión** muestran en qué se equivoca cada modelo (falsos positivos vs. falsos negativos), información que el AUC resume pero no detalla. Aquí el error más costoso es el **falso negativo**: clasificar como \"no deserta\" a un estudiante que sí está en riesgo, porque lo dejaría fuera del programa de tutoría.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_logistico, truth = deserto, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Regresión logística\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_knn, truth = deserto, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = paste0(\"Matriz de confusión — KNN (k = \", mejor_k$neighbors, \")\"))\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\nComo las clases están balanceadas (~37% de deserción), la métrica de decisión es el **AUC** (mayor es mejor). Ordenamos la tabla comparativa por AUC descendente e identificamos al ganador.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final <- metricas_comparacion %>%\n  mutate(across(where(is.numeric), ~ round(., 3))) %>%\n  arrange(desc(roc_auc))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_auc <- round(ganador$roc_auc - perdedor$roc_auc, 3)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              | accuracy| sensitivity|  spec| roc_auc|\n|:-------------------|--------:|-----------:|-----:|-------:|\n|Regresión logística |    0.797|       0.641| 0.887|   0.847|\n|KNN                 |    0.649|       0.043| 1.000|   0.782|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión logística.** Obtiene el mayor AUC en la base de prueba (0.847), frente a 0.782 del otro modelo (diferencia de 0.065 de AUC).\n\n> La ventaja de **Regresión logística** es clara (0.065 de AUC), por lo que es la elección recomendada para este problema.\n\nComo las clases están razonablemente balanceadas, el *accuracy* también es informativo aquí. Aun así, conviene vigilar la **sensibilidad** (recall sobre \"si\"): dejar fuera a un estudiante en riesgo es el error más costoso, así que entre modelos parejos en AUC preferiríamos el que detecte mejor los casos de deserción. En un problema desbalanceado habría que mirar recall y precision en lugar del accuracy.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}