{
  "hash": "5325f5f37ef0018f8e0eb88114b6ff7b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clasificación: aprobación de crédito\"\nsubtitle: \"EJERCICIO DE CLASIFICACIÓN — Regresión logística vs. KNN\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir si una solicitud de crédito de consumo será aprobada (`aprobado`: si/no) a partir del perfil financiero y sociodemográfico del solicitante. Compararemos dos clasificadores sobre el mismo flujo: una **regresión logística** (lineal, interpretable) y **KNN** (k-vecinos más cercanos, basado en distancias). Recorremos el flujo completo: partición, receta, `workflow()`, validación cruzada, tuning y evaluación honesta con `last_fit()`, y cerramos con una recomendación clara.\n\n## 1. Cargar librerías\n\nCargamos todo al inicio. `kknn` es el motor que `parsnip` usa por detrás para KNN; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(kknn)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nRemovemos `id_solicitud` (identificador, no predictor) y convertimos la objetivo a `factor`. Fijamos `\"si\"` como **primer nivel**: `yardstick` toma el primer nivel como el evento de interés, de modo que sensibilidad, AUC y demás métricas se calculen sobre \"aprobado = si\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreditos <- read_csv(\"datos.csv\") %>%\n  select(-id_solicitud) %>%\n  mutate(aprobado = factor(aprobado, levels = c(\"si\", \"no\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(creditos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 950\nColumns: 10\n$ edad                      <dbl> 19, 30, 24, 51, 25, 68, 39, 73, 22, 53, 59, …\n$ ingreso_mensual_mxn       <dbl> 45819, 7622, 39178, 13792, 7764, 22826, 2283…\n$ monto_solicitado_mxn      <dbl> 340000, 61000, 163000, 82000, 39000, 128000,…\n$ plazo_meses               <dbl> 36, 12, 6, 6, 24, 36, 12, 36, 24, 24, 24, 36…\n$ pago_mensual_estimado_mxn <dbl> 9444, 5083, 27167, 13667, 1625, 3556, 10583,…\n$ pct_deuda_ingreso         <dbl> 0.206, 0.667, 0.693, 0.991, 0.209, 0.156, 0.…\n$ score_historial           <dbl> 649, 641, 670, 716, 799, 626, 653, 771, 590,…\n$ num_creditos_activos      <dbl> 0, 0, 1, 1, 3, 3, 1, 0, 0, 1, 3, 0, 1, 1, 3,…\n$ antiguedad_empleo_anios   <dbl> 2.0, 9.7, 1.3, 7.0, 1.7, 2.7, 7.2, 20.1, 3.7…\n$ aprobado                  <fct> si, no, no, no, no, si, si, no, no, si, no, …\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nTres revisiones mínimas antes de modelar: el **balance de clases**, los **datos faltantes** y la **colinealidad**.\n\nEl balance importa porque, si una clase fuera muy rara, el *accuracy* dejaría de ser confiable (predecir siempre la mayoría daría un accuracy alto pero inútil). Aquí veremos que está casi balanceado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreditos %>%\n  group_by(aprobado) %>%\n  count() %>%\n  ungroup() %>%\n  mutate(porcentaje = 100 * (n / sum(n)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|aprobado |   n| porcentaje|\n|:--------|---:|----------:|\n|si       | 528|   55.57895|\n|no       | 422|   44.42105|\n\n</div>\n:::\n:::\n\n\nContamos los `NA`: esto guía la imputación. Esperamos faltantes en `ingreso_mensual_mxn` y `score_historial`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncreditos %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable                  | n_na|\n|:-------------------------|----:|\n|ingreso_mensual_mxn       |   47|\n|score_historial           |   38|\n|edad                      |    0|\n|monto_solicitado_mxn      |    0|\n|plazo_meses               |    0|\n|pago_mensual_estimado_mxn |    0|\n|pct_deuda_ingreso         |    0|\n|num_creditos_activos      |    0|\n|antiguedad_empleo_anios   |    0|\n|aprobado                  |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación revela colinealidad: `monto_solicitado_mxn`, `pago_mensual_estimado_mxn` y `pct_deuda_ingreso` se derivan unas de otras. En KNN, dos variables redundantes harían que esa información pese doble en la distancia; por eso luego las filtramos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatriz_correlacion <- creditos %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba (estratificada)\n\nSeparamos 75% para entrenamiento y 25% para prueba. **Estratificamos** por `aprobado` para que ambas particiones conserven la misma proporción de clases. La prueba se reserva para el final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncreditos_split <- initial_split(creditos, prop = 0.75, strata = aprobado)\ncreditos_entrenamiento <- creditos_split %>% training()\ncreditos_prueba <- creditos_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(creditos_entrenamiento$aprobado) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.5561798 0.4438202 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(creditos_prueba$aprobado) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.5546218 0.4453782 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que ambos modelos vean la misma representación de los datos.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden?\nUna **receta** encadena pasos (`step_*`) que se aprenden solo con el entrenamiento y se aplican igual a la prueba (evita fuga de información). El orden importa: imputamos primero (los pasos siguientes no toleran `NA`), filtramos colinealidad y **normalizamos**, que es indispensable para KNN.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## ¿Por qué normalizar para KNN?\nKNN clasifica por **distancia** entre observaciones. Sin estandarizar, una variable de gran escala (montos en miles de pesos) aplastaría a otras de escala pequeña (número de créditos) en el cálculo de distancias. `step_normalize` deja todas las variables en media 0 y desviación 1.\n:::\n\nTodos los predictores son numéricos, así que no hace falta `step_dummy`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_creditos <- recipe(aprobado ~ ., data = creditos_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%   # imputar NAs\n  step_nzv(all_predictors()) %>%                      # quitar casi-constantes\n  step_corr(all_numeric_predictors(), threshold = 0.7) %>%  # colinealidad\n  step_normalize(all_numeric_predictors()) %>%        # estandarizar (clave KNN)\n  step_zv(all_predictors())                           # red de seguridad\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_creditos %>%\n  prep(training = creditos_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 712\nColumns: 8\n$ edad                    <dbl> -0.96044958, -1.31982950, 0.29738016, -1.25993…\n$ ingreso_mensual_mxn     <dbl> -1.26148623, 0.78763404, -0.86083114, -1.25226…\n$ plazo_meses             <dbl> -0.9701442, -1.3465708, -1.3465708, -0.2172912…\n$ pct_deuda_ingreso       <dbl> 1.50978362, 1.61010420, 2.75993244, -0.2574020…\n$ score_historial         <dbl> -0.08607179, 0.25199369, 0.78823549, 1.7558022…\n$ num_creditos_activos    <dbl> -1.2386027, -0.4931377, -0.4931377, 0.9977924,…\n$ antiguedad_empleo_anios <dbl> 1.06079890, -1.10497773, 0.36465641, -1.001845…\n$ aprobado                <fct> no, no, no, no, no, no, no, no, no, no, no, no…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nEl primer modelo es la **regresión logística**: no tiene hiperparámetros que ajustar. Modela el log-odds de aprobación como combinación lineal de los predictores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEl segundo es **KNN**, donde ajustaremos el número de vecinos `k`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es KNN y qué controla k?\n**KNN** clasifica una observación nueva según la clase mayoritaria de sus `k` vecinos más cercanos en el espacio de predictores. `k` gobierna el equilibrio sesgo-varianza: un `k` muy chico sobreajusta al ruido (frontera muy flexible), uno muy grande subajusta (frontera demasiado suave). Usamos `weight_func = \"rectangular\"` (voto no ponderado) para que ese equilibrio se vea con claridad y el `k` óptimo caiga en un valor intermedio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_knn <- nearest_neighbor(\n    neighbors = tune(),\n    weight_func = \"rectangular\"\n  ) %>%\n  set_engine(\"kknn\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEmpaquetamos cada modelo con la misma receta en su `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** une la receta y el modelo en un objeto. `fit()` aplica internamente `prep` + `bake` + `fit`, y `predict()` repite el mismo preprocesamiento sobre datos nuevos. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_logistico <- workflow() %>%\n  add_recipe(receta_creditos) %>%\n  add_model(modelo_logistico)\n\nworkflow_knn <- workflow() %>%\n  add_recipe(receta_creditos) %>%\n  add_model(modelo_knn)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` folds. En cada ronda entrenamos con `v − 1` y validamos en el restante, rotando; promediamos el desempeño. Estima la generalización **sin tocar la prueba**, y sirve tanto para comparar modelos como para elegir hiperparámetros.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(creditos_entrenamiento, v = 5, strata = aprobado)\n```\n:::\n\n\nDefinimos las métricas de clasificación.\n\n::: {.callout-note collapse=\"true\"}\n## Matriz de confusión, sensibilidad, especificidad, ROC y AUC\n- **Matriz de confusión:** tabla que cruza la clase real con la predicha (verdaderos/falsos positivos y negativos).\n- **Sensibilidad (recall):** de los positivos reales, cuántos detecta el modelo.\n- **Especificidad:** de los negativos reales, cuántos clasifica bien.\n- **Curva ROC:** traza sensibilidad vs. (1 − especificidad) variando el umbral de decisión.\n- **AUC:** área bajo la curva ROC; resume la discriminación (0.5 = azar, 1 = perfecto) sin depender de un umbral fijo. Es nuestra métrica principal.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_clasificacion <- metric_set(roc_auc, accuracy, sensitivity,\n                                     yardstick::spec)\n```\n:::\n\n\nLa logística no se tunea: estimamos su desempeño en CV con `fit_resamples()`.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\n`fit_resamples()` evalúa en CV un modelo **sin** hiperparámetros (la logística). `tune_grid()` prueba varias combinaciones de hiperparámetros (el `k` de KNN) y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_logistico <- workflow_logistico %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_clasificacion)\n\ncollect_metrics(cv_logistico)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric     |.estimator |      mean|  n|   std_err|.config         |\n|:-----------|:----------|---------:|--:|---------:|:---------------|\n|accuracy    |binary     | 0.6685446|  5| 0.0054751|pre0_mod0_post0 |\n|roc_auc     |binary     | 0.6764716|  5| 0.0084346|pre0_mod0_post0 |\n|sensitivity |binary     | 0.8359810|  5| 0.0160954|pre0_mod0_post0 |\n|spec        |binary     | 0.4586806|  5| 0.0150951|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara KNN definimos una grilla de valores de `k` y corremos la validación cruzada en cada uno.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_k <- grid_regular(neighbors(range = c(1, 101)), levels = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_knn <- workflow_knn %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_k,\n            metrics = metricas_clasificacion)\n```\n:::\n\n\nLa gráfica de AUC promedio vs. `k` (con barras de error ±1 error estándar) muestra el equilibrio sesgo-varianza: el AUC sube de un `k` muy chico hacia un `k` intermedio y vuelve a bajar con `k` muy grande. Elegimos el `k` del máximo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_knn %>%\n  collect_metrics() %>%\n  filter(.metric == \"roc_auc\") %>%\n  ggplot(aes(x = neighbors, y = mean)) +\n  geom_line() +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err),\n                width = 1.5) +\n  labs(title = \"AUC promedio por valor de k (validación cruzada 5-fold)\",\n       x = \"k (número de vecinos)\", y = \"AUC promedio\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_k <- tuning_knn %>% select_best(metric = \"roc_auc\")\nmejor_k\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| neighbors|.config          |\n|---------:|:----------------|\n|        46|pre0_mod06_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa logística ya está lista; al KNN le inyectamos el `k` ganador con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_knn_final <- workflow_knn %>%\n  finalize_workflow(mejor_k)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` reentrena el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la prueba reservada. Da la estimación honesta del desempeño en datos no vistos.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_logistico <- workflow_logistico %>%\n  last_fit(split = creditos_split, metrics = metricas_clasificacion)\n\najuste_knn <- workflow_knn_final %>%\n  last_fit(split = creditos_split, metrics = metricas_clasificacion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de ambos modelos en la prueba en una sola tabla, ordenada por AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_logistico) %>% mutate(modelo = \"Regresión logística\"),\n    collect_metrics(ajuste_knn) %>% mutate(modelo = \"KNN\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(desc(roc_auc))\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              |  accuracy| sensitivity|      spec|   roc_auc|\n|:-------------------|---------:|-----------:|---------:|---------:|\n|KNN                 | 0.6470588|   0.9621212| 0.2547170| 0.7246284|\n|Regresión logística | 0.6554622|   0.8409091| 0.4245283| 0.5829045|\n\n</div>\n:::\n:::\n\n\nLas **curvas ROC sobrepuestas** comparan visualmente la discriminación: entre más se acerque una curva a la esquina superior izquierda, mejor separa aprobados de rechazados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_logistico <- collect_predictions(ajuste_logistico) %>%\n  mutate(modelo = \"Regresión logística\")\npreds_knn <- collect_predictions(ajuste_knn) %>%\n  mutate(modelo = \"KNN\")\n\npreds_ambos <- bind_rows(preds_logistico, preds_knn)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  group_by(modelo) %>%\n  roc_curve(truth = aprobado, .pred_si) %>%\n  autoplot() +\n  labs(title = \"Curvas ROC en la base de prueba\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\nLas **matrices de confusión** muestran en qué se equivoca cada modelo (falsos positivos vs. falsos negativos), información que el AUC resume pero no detalla.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_logistico, truth = aprobado, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Regresión logística\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_knn, truth = aprobado, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = paste0(\"Matriz de confusión — KNN (k = \", mejor_k$neighbors, \")\"))\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final <- metricas_comparacion %>%\n  mutate(across(where(is.numeric), ~ round(., 3))) %>%\n  arrange(desc(roc_auc))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_auc <- round(ganador$roc_auc - perdedor$roc_auc, 3)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              | accuracy| sensitivity|  spec| roc_auc|\n|:-------------------|--------:|-----------:|-----:|-------:|\n|KNN                 |    0.647|       0.962| 0.255|   0.725|\n|Regresión logística |    0.655|       0.841| 0.425|   0.583|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: KNN.** Obtiene el mayor AUC en la base de prueba (0.725), frente a 0.583 del otro modelo (diferencia de 0.142).\n\n> La ventaja de **KNN** es clara (0.142 de AUC), por lo que es la elección recomendada para este problema.\n\nComo las clases están casi balanceadas, el *accuracy* también es informativo aquí; en problemas desbalanceados habría que mirar recall y precision en su lugar.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}