{
  "hash": "8afc91178a53a792d47562c39cb3b0ab",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clasificación: potabilidad del agua\"\nsubtitle: \"EJERCICIO DE CLASIFICACIÓN — Regresión logística vs. KNN\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir si una muestra de agua es apta para consumo (`potable`: si/no) a partir de su análisis fisicoquímico. Compararemos dos clasificadores sobre el mismo flujo: una **regresión logística** (lineal, interpretable) y **KNN** (k-vecinos más cercanos, basado en distancias). Todos los predictores son numéricos pero en **escalas muy distintas**: el pH va de 0 a 14, mientras que los sólidos disueltos llegan a miles de mg/L. Esa disparidad de escalas hace que normalizar sea indispensable para KNN, como veremos. Recorremos el flujo completo: partición, receta, `workflow()`, validación cruzada, tuning del número de vecinos y evaluación honesta con `last_fit()`, y cerramos con una recomendación clara.\n\n## 1. Cargar librerías\n\nCargamos todo al inicio. `kknn` es el motor que `parsnip` usa por detrás para KNN; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(kknn)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nNo hay columna identificadora que descartar. Convertimos la objetivo a `factor` y fijamos `\"si\"` (potable) como **primer nivel**: `yardstick` toma el primer nivel como el evento de interés, de modo que sensibilidad, AUC y demás métricas se calculen sobre \"potable = si\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# No hay columna identificadora. Convertimos la objetivo a factor con \"si\"\n# (potable) como PRIMER nivel = evento de interés.\nagua <- read_csv(\"datos.csv\") %>%\n  mutate(potable = factor(potable, levels = c(\"si\", \"no\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(agua)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 820\nColumns: 10\n$ ph                    <dbl> 5.59, 6.34, 8.04, 6.16, 7.26, 6.45, 6.78, 7.53, …\n$ dureza_mg_l           <dbl> 191.1, 175.2, 220.6, 185.9, 165.2, 197.2, 141.5,…\n$ solidos_disueltos_ppm <dbl> 22720, 27408, 11398, 25524, 23984, 22462, 26823,…\n$ cloraminas_ppm        <dbl> 9.98, 8.93, 6.98, 10.48, 4.00, 5.23, 6.10, 6.30,…\n$ sulfatos_mg_l         <dbl> 313.7, 279.0, 288.5, 384.2, 283.5, 302.6, 342.6,…\n$ conductividad_us_cm   <dbl> 435.6, 529.6, 234.0, 486.9, 442.5, 423.3, 525.5,…\n$ carbono_organico_ppm  <dbl> 12.81, 9.74, 17.25, 19.12, 16.62, 11.61, 14.17, …\n$ trihalometanos_ug_l   <dbl> 33.4, 44.8, 101.2, 64.1, 84.5, 64.8, 69.2, 57.9,…\n$ turbidez_ntu          <dbl> 3.83, 3.84, 4.11, 4.26, 4.56, 3.71, 2.63, 4.49, …\n$ potable               <fct> no, si, no, no, no, si, no, si, no, no, si, si, …\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nTres revisiones mínimas antes de modelar: el **balance de clases**, los **datos faltantes** y la **colinealidad**.\n\nEl balance importa porque, si una clase fuera muy rara, el *accuracy* dejaría de ser confiable (predecir siempre la mayoría daría un accuracy alto pero inútil). Aquí veremos que está razonablemente balanceado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagua %>%\n  group_by(potable) %>%\n  count() %>%\n  ungroup() %>%\n  mutate(porcentaje = 100 * (n / sum(n)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|potable |   n| porcentaje|\n|:-------|---:|----------:|\n|si      | 340|   41.46341|\n|no      | 480|   58.53659|\n\n</div>\n:::\n:::\n\n\nContamos los `NA`: esto guía la imputación. Son habituales los faltantes en el pH y en los sulfatos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagua %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable              | n_na|\n|:---------------------|----:|\n|sulfatos_mg_l         |   49|\n|ph                    |   24|\n|dureza_mg_l           |    0|\n|solidos_disueltos_ppm |    0|\n|cloraminas_ppm        |    0|\n|conductividad_us_cm   |    0|\n|carbono_organico_ppm  |    0|\n|trihalometanos_ug_l   |    0|\n|turbidez_ntu          |    0|\n|potable               |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación revela colinealidad: la conductividad y los sólidos disueltos miden carga iónica parecida, así que tienden a moverse juntas. En KNN, dos variables redundantes harían que esa información pese doble en el cálculo de distancias; por eso luego las filtramos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colinealidad: conductividad y sólidos disueltos miden carga iónica parecida.\nmatriz_correlacion <- agua %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba (estratificada)\n\nSeparamos 75% para entrenamiento y 25% para prueba. **Estratificamos** por `potable` para que ambas particiones conserven la misma proporción de clases. La prueba se reserva para el final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nagua_split <- initial_split(agua, prop = 0.75, strata = potable)\nagua_entrenamiento <- agua_split %>% training()\nagua_prueba <- agua_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(agua_entrenamiento$potable) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4146341 0.5853659 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(agua_prueba$potable) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4146341 0.5853659 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que ambos modelos vean la misma representación de los datos.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se aprenden solo con el entrenamiento y se aplican igual a la prueba (esto evita fuga de información). El orden importa: se imputan los `NA` primero (los pasos siguientes no los toleran), se filtra colinealidad y se normaliza antes de crear *dummies*, y `step_zv` queda al final como red de seguridad.\n:::\n\n::: {.callout-note collapse=\"true\"}\n## ¿Por qué normalizar para KNN?\nKNN clasifica por **distancia** entre observaciones. Sin estandarizar, una variable de gran escala (sólidos disueltos en miles de mg/L) aplastaría a otras de escala pequeña (el pH, que va de 0 a 14, o la turbidez) en el cálculo de distancias: prácticamente solo importarían los sólidos. `step_normalize` deja todas las variables en media 0 y desviación 1, para que cada una contribuya de forma comparable. Por eso, en este problema con escalas tan dispares, normalizar no es un lujo: es lo que hace que KNN funcione.\n:::\n\nTodos los predictores son numéricos, así que no hace falta `step_dummy`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Todos los predictores son numéricos. El orden importa:\n#  1. step_impute_median: rellenar NAs (ph y sulfatos).\n#  2. step_nzv: quitar casi-constantes.\n#  3. step_corr: filtrar colinealidad (umbral 0.7); descarta una de las dos\n#     variables iónicas redundantes.\n#  4. step_normalize: estandarizar. ES CRÍTICO para KNN (sin esto, los sólidos\n#     disueltos aplastarían al pH y la turbidez en la distancia).\n#  5. step_zv: por seguridad.\nreceta_agua <- recipe(potable ~ ., data = agua_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.7) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nAplicamos la receta al entrenamiento para revisar que las variables quedaron numéricas, sin `NA` y estandarizadas (media cercana a 0).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_agua %>%\n  prep(training = agua_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 615\nColumns: 9\n$ ph                   <dbl> -1.0529594, 0.7134422, -0.6420007, 0.1510776, 0.6…\n$ dureza_mg_l          <dbl> -0.15288719, 0.74511717, -0.31117948, -0.94130458…\n$ cloraminas_ppm       <dbl> 1.745294527, -0.120903322, 2.056327501, -1.974659…\n$ sulfatos_mg_l        <dbl> -0.47834080, -1.07958864, 1.20372161, -1.19888385…\n$ conductividad_us_cm  <dbl> 0.040909321, -1.158963245, 0.346234037, 0.0819763…\n$ carbono_organico_ppm <dbl> -0.3584871, 1.0035912, 1.5772592, 0.8103233, -1.3…\n$ trihalometanos_ug_l  <dbl> -2.02229195, 2.10730639, -0.15240007, 1.09013394,…\n$ turbidez_ntu         <dbl> -0.2187150, 0.1338662, 0.3227489, 0.7005145, -1.1…\n$ potable              <fct> no, no, no, no, no, no, no, no, no, no, no, no, n…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nEl primer modelo es la **regresión logística**: no tiene hiperparámetros que ajustar. Modela el log-odds de potabilidad como combinación lineal de los predictores fisicoquímicos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEl segundo es **KNN**, donde ajustaremos el número de vecinos `k`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es KNN y qué controla k?\n**KNN** clasifica una observación nueva según la clase mayoritaria de sus `k` vecinos más cercanos en el espacio de predictores. `k` gobierna el equilibrio sesgo-varianza: un `k` muy chico sobreajusta al ruido (frontera muy flexible), uno muy grande subajusta (frontera demasiado suave). Usamos `weight_func = \"rectangular\"` (voto no ponderado) para que ese equilibrio se vea con claridad y el `k` óptimo caiga en un valor intermedio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_knn <- nearest_neighbor(\n    neighbors = tune(),\n    weight_func = \"rectangular\"\n  ) %>%\n  set_engine(\"kknn\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEmpaquetamos cada modelo con la misma receta en su `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_logistico <- workflow() %>%\n  add_recipe(receta_agua) %>%\n  add_model(modelo_logistico)\n\nworkflow_knn <- workflow() %>%\n  add_recipe(receta_agua) %>%\n  add_model(modelo_knn)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y validamos en el restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(agua_entrenamiento, v = 5, strata = potable)\n```\n:::\n\n\nDefinimos las métricas de clasificación. Reportamos AUC (métrica principal), accuracy, sensibilidad y especificidad.\n\n::: {.callout-note collapse=\"true\"}\n## Matriz de confusión, sensibilidad, especificidad, ROC y AUC\n- **Matriz de confusión:** tabla que cruza la clase real con la predicha (verdaderos/falsos positivos y negativos).\n- **Sensibilidad (recall):** de los positivos reales, cuántos detecta el modelo.\n- **Especificidad:** de los negativos reales, cuántos clasifica bien. En seguridad sanitaria es la métrica a vigilar: mide cuántas aguas NO potables se identifican como tales.\n- **Curva ROC:** traza sensibilidad vs. (1 − especificidad) variando el umbral de decisión.\n- **AUC:** área bajo la curva ROC; resume la discriminación (0.5 = azar, 1 = perfecto) sin depender de un umbral fijo. Es la métrica principal cuando las clases están balanceadas.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_clasificacion <- metric_set(roc_auc, accuracy, sensitivity,\n                                     yardstick::spec)\n```\n:::\n\n\nLa logística no se tunea: estimamos su desempeño en CV con `fit_resamples()`.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (la regresión logística), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el `k` de KNN), `tune_grid()` prueba varias combinaciones en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_logistico <- workflow_logistico %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_clasificacion)\n\ncollect_metrics(cv_logistico)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric     |.estimator |      mean|  n|   std_err|.config         |\n|:-----------|:----------|---------:|--:|---------:|:---------------|\n|accuracy    |binary     | 0.5739837|  5| 0.0181066|pre0_mod0_post0 |\n|roc_auc     |binary     | 0.6052832|  5| 0.0165734|pre0_mod0_post0 |\n|sensitivity |binary     | 0.2823529|  5| 0.0466485|pre0_mod0_post0 |\n|spec        |binary     | 0.7805556|  5| 0.0261318|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara KNN definimos una grilla de valores de `k` y corremos la validación cruzada en cada uno.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_k <- grid_regular(neighbors(range = c(1, 101)), levels = 12)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_knn <- workflow_knn %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_k,\n            metrics = metricas_clasificacion)\n```\n:::\n\n\nLa gráfica de AUC promedio vs. `k` (con barras de error ±1 error estándar) muestra el equilibrio sesgo-varianza: el AUC sube de un `k` muy chico hacia un `k` intermedio y vuelve a bajar con `k` muy grande. Elegimos el `k` del máximo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_knn %>%\n  collect_metrics() %>%\n  filter(.metric == \"roc_auc\") %>%\n  ggplot(aes(x = neighbors, y = mean)) +\n  geom_line() +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = mean - std_err, ymax = mean + std_err),\n                width = 1.5) +\n  labs(title = \"AUC promedio por valor de k (validación cruzada 5-fold)\",\n       x = \"k (número de vecinos)\", y = \"AUC promedio\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-21-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_k <- tuning_knn %>% select_best(metric = \"roc_auc\")\nmejor_k\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| neighbors|.config          |\n|---------:|:----------------|\n|        28|pre0_mod04_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa logística ya está lista; al KNN le inyectamos el `k` ganador con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_knn_final <- workflow_knn %>%\n  finalize_workflow(mejor_k)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_logistico <- workflow_logistico %>%\n  last_fit(split = agua_split, metrics = metricas_clasificacion)\n\najuste_knn <- workflow_knn_final %>%\n  last_fit(split = agua_split, metrics = metricas_clasificacion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de ambos modelos en la prueba en una sola tabla, ordenada por AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_logistico) %>% mutate(modelo = \"Regresión logística\"),\n    collect_metrics(ajuste_knn) %>% mutate(modelo = \"KNN\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(desc(roc_auc))\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              |  accuracy| sensitivity|      spec|   roc_auc|\n|:-------------------|---------:|-----------:|---------:|---------:|\n|KNN                 | 0.7170732|   0.7882353| 0.6666667| 0.7927451|\n|Regresión logística | 0.5658537|   0.2470588| 0.7916667| 0.6129412|\n\n</div>\n:::\n:::\n\n\nLas **curvas ROC sobrepuestas** comparan visualmente la discriminación: entre más se acerque una curva a la esquina superior izquierda, mejor separa el modelo las aguas potables de las no potables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_logistico <- collect_predictions(ajuste_logistico) %>%\n  mutate(modelo = \"Regresión logística\")\npreds_knn <- collect_predictions(ajuste_knn) %>%\n  mutate(modelo = \"KNN\")\n\npreds_ambos <- bind_rows(preds_logistico, preds_knn)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  group_by(modelo) %>%\n  roc_curve(truth = potable, .pred_si) %>%\n  autoplot() +\n  labs(title = \"Curvas ROC en la base de prueba\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\nLas **matrices de confusión** muestran en qué se equivoca cada modelo (falsos positivos vs. falsos negativos), información que el AUC resume pero no detalla. Aquí el error más grave es el **falso positivo sanitario**: declarar potable un agua que en realidad no lo es. Ese error vive en la fila/columna de la clase \"si\" predicha cuando la verdad es \"no\", y es justo lo que penaliza una baja **especificidad**. Por eso, además del AUC, conviene mirar qué modelo comete menos errores de ese tipo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_logistico, truth = potable, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Regresión logística\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_knn, truth = potable, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = paste0(\"Matriz de confusión — KNN (k = \", mejor_k$neighbors, \")\"))\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\nOrdenamos la tabla de métricas por AUC (mayor es mejor) y comparamos al ganador con el segundo lugar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final <- metricas_comparacion %>%\n  mutate(across(where(is.numeric), ~ round(., 3))) %>%\n  arrange(desc(roc_auc))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_auc <- round(ganador$roc_auc - perdedor$roc_auc, 3)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              | accuracy| sensitivity|  spec| roc_auc|\n|:-------------------|--------:|-----------:|-----:|-------:|\n|KNN                 |    0.717|       0.788| 0.667|   0.793|\n|Regresión logística |    0.566|       0.247| 0.792|   0.613|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: KNN.** Obtiene el mayor AUC en la base de prueba (0.793), frente a 0.613 del otro modelo (diferencia de 0.18).\n\n> La ventaja de **KNN** es clara (0.18 de AUC), por lo que es la elección recomendada para este problema.\n\nComo las clases están razonablemente balanceadas, el AUC es la métrica de decisión adecuada y el *accuracy* también resulta informativo. Pero hay un matiz importante del dominio: por **seguridad sanitaria**, entre dos modelos con AUC parecido conviene preferir el que tenga mayor **especificidad**, porque el error costoso es declarar potable un agua que no lo es. Revisa esa columna en la tabla y las matrices de confusión antes de cerrar la recomendación.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}