{
  "hash": "f56eaa5072694196f19c7df14ceaec01",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Clasificación: aprobación de seguro de vida\"\nsubtitle: \"EJERCICIO DE CLASIFICACIÓN — Regresión logística vs. XGBoost\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir si una solicitud de póliza de seguro de vida será aprobada (`aprobada`: si/no) a partir de información demográfica, clínica e historial del solicitante. Compararemos dos clasificadores sobre el mismo flujo: una **regresión logística** (lineal, interpretable) y **XGBoost** (boosting de árboles, gran capacidad predictiva). El dataset mezcla variables numéricas (edad, IMC, presión, colesterol) y categóricas (sexo, fumador, región), así que la receta tendrá que crear variables *dummy*. Recorremos el flujo completo: partición, receta, `workflow()`, validación cruzada, tuning y evaluación honesta con `last_fit()`, y cerramos con una recomendación clara.\n\n## 1. Cargar librerías\n\nCargamos todo al inicio. `xgboost` es el motor que `parsnip` usa por detrás para el boosting; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(xgboost)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nRemovemos `id_solicitante` (identificador, no predictor) y convertimos la objetivo a `factor`. Fijamos `\"si\"` como **primer nivel**: `yardstick` toma el primer nivel como el evento de interés, de modo que sensibilidad, AUC y demás métricas se calculen sobre \"aprobada = si\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removemos id_solicitante (identificador). Convertimos la objetivo a factor\n# con \"si\" (aprobada) como PRIMER nivel = evento de interés.\nseguros <- read_csv(\"datos.csv\") %>%\n  select(-id_solicitante) %>%\n  mutate(aprobada = factor(aprobada, levels = c(\"si\", \"no\")))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(seguros)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 880\nColumns: 11\n$ edad                      <dbl> 25, 58, 21, 47, 67, 33, 53, 52, 18, 52, 63, …\n$ sexo                      <chr> \"M\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\",…\n$ imc                       <dbl> 29.2, 28.4, 25.3, 31.9, 27.8, 24.8, 17.1, 22…\n$ fumador                   <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"si\", \"no\", \"n…\n$ num_padecimientos_previos <dbl> 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,…\n$ presion_sistolica         <dbl> 105, 139, 124, 133, 118, 144, 143, 136, 118,…\n$ colesterol_mg_dl          <dbl> 212, NA, 191, 204, 161, 236, 182, 226, 156, …\n$ antecedente_familiar      <chr> \"no\", \"si\", \"no\", \"no\", \"no\", \"si\", \"no\", \"n…\n$ meses_como_cliente        <dbl> 15, 64, 38, 34, 22, 38, 43, 14, 80, 77, 16, …\n$ region                    <chr> \"norte\", \"bajio\", \"centro\", \"bajio\", \"sur\", …\n$ aprobada                  <fct> si, si, no, si, no, si, no, no, no, si, no, …\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nTres revisiones mínimas antes de modelar: el **balance de clases**, los **datos faltantes** y la **colinealidad**.\n\nEl balance importa porque, si una clase fuera muy rara, el *accuracy* dejaría de ser confiable (predecir siempre la mayoría daría un accuracy alto pero inútil). Aquí veremos que está razonablemente balanceado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseguros %>%\n  group_by(aprobada) %>%\n  count() %>%\n  ungroup() %>%\n  mutate(porcentaje = 100 * (n / sum(n)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|aprobada |   n| porcentaje|\n|:--------|---:|----------:|\n|si       | 404|   45.90909|\n|no       | 476|   54.09091|\n\n</div>\n:::\n:::\n\n\nContamos los `NA`: esto guía la imputación. Esperamos faltantes sobre todo en variables clínicas como el colesterol.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseguros %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable                  | n_na|\n|:-------------------------|----:|\n|colesterol_mg_dl          |   44|\n|edad                      |    0|\n|sexo                      |    0|\n|imc                       |    0|\n|fumador                   |    0|\n|num_padecimientos_previos |    0|\n|presion_sistolica         |    0|\n|antecedente_familiar      |    0|\n|meses_como_cliente        |    0|\n|region                    |    0|\n|aprobada                  |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación revela colinealidad clínica: edad, presión y colesterol tienden a moverse juntas. Variables redundantes inflan artificialmente el peso de esa información compartida, por eso luego las filtramos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colinealidad clínica: edad, presión y colesterol tienden a moverse juntas.\nmatriz_correlacion <- seguros %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba (estratificada)\n\nSeparamos 75% para entrenamiento y 25% para prueba. **Estratificamos** por `aprobada` para que ambas particiones conserven la misma proporción de clases. La prueba se reserva para el final.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nseguros_split <- initial_split(seguros, prop = 0.75, strata = aprobada)\nseguros_entrenamiento <- seguros_split %>% training()\nseguros_prueba <- seguros_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(seguros_entrenamiento$aprobada) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4590909 0.5409091 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(seguros_prueba$aprobada) %>% prop.table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n       si        no \n0.4590909 0.5409091 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que ambos modelos vean la misma representación de los datos. Como el dataset mezcla numéricas y categóricas, el paso clave es `step_dummy`, que convierte cada categoría (sexo, fumador, región) en columnas binarias 0/1 que los modelos pueden procesar.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se aprenden solo con el entrenamiento y se aplican igual a la prueba (esto evita fuga de información). El orden importa: se imputan los `NA` primero (los pasos siguientes no los toleran), se filtra colinealidad y se normaliza antes de crear *dummies*, y `step_zv` queda al final como red de seguridad.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Receta única comparable:\n#  1. Imputar numéricos (mediana; colesterol tiene NAs) y nominales (moda).\n#  2. step_nzv: quitar casi-constantes.\n#  3. step_corr: filtrar colinealidad clínica.\n#  4. step_normalize: estandarizar numéricos.\n#  5. step_dummy: codificar sexo, fumador, antecedente_familiar, region.\n#  6. step_zv: por seguridad.\nreceta_seguros <- recipe(aprobada ~ ., data = seguros_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nComprobamos cómo queda la base ya horneada: todas las categóricas convertidas en columnas *dummy* y las numéricas estandarizadas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_seguros %>%\n  prep(training = seguros_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 660\nColumns: 13\n$ edad                      <dbl> -1.635693731, 1.483435826, 0.534135526, 0.46…\n$ imc                       <dbl> -0.494507896, -0.005600215, -2.098125089, -1…\n$ num_padecimientos_previos <dbl> 1.5450457, 0.3396909, 0.3396909, -0.8656639,…\n$ presion_sistolica         <dbl> 0.10342157, -0.30943066, 1.41078695, 0.92912…\n$ colesterol_mg_dl          <dbl> -0.30903359, -1.17450250, -0.56867426, 0.700…\n$ meses_como_cliente        <dbl> 0.09231233, -0.53538773, 0.28846860, -0.8492…\n$ aprobada                  <fct> no, no, no, no, no, no, no, no, no, no, no, …\n$ sexo_M                    <dbl> 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,…\n$ fumador_si                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…\n$ antecedente_familiar_si   <dbl> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,…\n$ region_centro             <dbl> 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,…\n$ region_norte              <dbl> 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,…\n$ region_sur                <dbl> 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nEl primer modelo es la **regresión logística**: no tiene hiperparámetros que ajustar. Modela el log-odds de aprobación como combinación lineal de los predictores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_logistico <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEl segundo es **XGBoost**, donde ajustaremos tres hiperparámetros clave: profundidad de los árboles, tasa de aprendizaje y reducción de pérdida mínima por corte.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es XGBoost (boosting)?\n**XGBoost** construye árboles en **secuencia**: cada árbol nuevo corrige los errores del conjunto anterior. El boosting reduce sobre todo el **sesgo** y suele dar el mejor desempeño predictivo, a costa de más hiperparámetros y mayor riesgo de sobreajuste. Se ajustan `tree_depth`, `learn_rate` y `loss_reduction`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_xgb <- boost_tree(\n    trees = 500,\n    tree_depth = tune(),\n    learn_rate = tune(),\n    loss_reduction = tune()\n  ) %>%\n  set_engine(\"xgboost\") %>%\n  set_mode(\"classification\")\n```\n:::\n\n\nEmpaquetamos cada modelo con la misma receta en su `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_logistico <- workflow() %>%\n  add_recipe(receta_seguros) %>%\n  add_model(modelo_logistico)\n\nworkflow_xgb <- workflow() %>%\n  add_recipe(receta_seguros) %>%\n  add_model(modelo_xgb)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y validamos en el restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(seguros_entrenamiento, v = 5, strata = aprobada)\n```\n:::\n\n\nDefinimos las métricas de clasificación. La principal será el AUC.\n\n::: {.callout-note collapse=\"true\"}\n## Matriz de confusión, sensibilidad, especificidad, ROC y AUC\n- **Matriz de confusión:** tabla que cruza la clase real con la predicha (verdaderos/falsos positivos y negativos).\n- **Sensibilidad (recall):** de los positivos reales, cuántos detecta el modelo.\n- **Especificidad:** de los negativos reales, cuántos clasifica bien.\n- **Curva ROC:** traza sensibilidad vs. (1 − especificidad) variando el umbral de decisión.\n- **AUC:** área bajo la curva ROC; resume la discriminación (0.5 = azar, 1 = perfecto) sin depender de un umbral fijo. Es la métrica principal cuando las clases están balanceadas.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_clasificacion <- metric_set(roc_auc, accuracy, sensitivity,\n                                     yardstick::spec)\n```\n:::\n\n\nLa logística no se tunea: estimamos su desempeño en CV con `fit_resamples()`.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (regresión lineal o logística), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene, `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_logistico <- workflow_logistico %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_clasificacion)\n\ncollect_metrics(cv_logistico)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric     |.estimator |      mean|  n|   std_err|.config         |\n|:-----------|:----------|---------:|--:|---------:|:---------------|\n|accuracy    |binary     | 0.6213328|  5| 0.0220540|pre0_mod0_post0 |\n|roc_auc     |binary     | 0.6467326|  5| 0.0253323|pre0_mod0_post0 |\n|sensitivity |binary     | 0.5514754|  5| 0.0213553|pre0_mod0_post0 |\n|spec        |binary     | 0.6806729|  5| 0.0287420|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara XGBoost pedimos a `tune_grid()` que pruebe 12 combinaciones de hiperparámetros con la validación cruzada y escogemos la de mayor AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_xgb <- workflow_xgb %>%\n  tune_grid(resamples = folds_cv,\n            grid = 12,\n            metrics = metricas_clasificacion)\n```\n:::\n\n\nLa gráfica muestra cómo varía el AUC promedio según los valores de los hiperparámetros; nos ayuda a ver qué combinaciones funcionan mejor antes de quedarnos con la ganadora.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(tuning_xgb, metric = \"roc_auc\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-20-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_xgb <- tuning_xgb %>% select_best(metric = \"roc_auc\")\nmejor_xgb\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| tree_depth| learn_rate| loss_reduction|.config          |\n|----------:|----------:|--------------:|:----------------|\n|          3|  0.0081113|       2.848036|pre0_mod03_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa logística ya está lista; a XGBoost le inyectamos los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_xgb_final <- workflow_xgb %>%\n  finalize_workflow(mejor_xgb)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_logistico <- workflow_logistico %>%\n  last_fit(split = seguros_split, metrics = metricas_clasificacion)\n\najuste_xgb <- workflow_xgb_final %>%\n  last_fit(split = seguros_split, metrics = metricas_clasificacion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de ambos modelos en la prueba en una sola tabla, ordenada por AUC.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_logistico) %>% mutate(modelo = \"Regresión logística\"),\n    collect_metrics(ajuste_xgb) %>% mutate(modelo = \"XGBoost\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(desc(roc_auc))\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              |  accuracy| sensitivity|      spec|   roc_auc|\n|:-------------------|---------:|-----------:|---------:|---------:|\n|XGBoost             | 0.7681818|   0.7326733| 0.7983193| 0.8486563|\n|Regresión logística | 0.5363636|   0.4059406| 0.6470588| 0.5607788|\n\n</div>\n:::\n:::\n\n\nLas **curvas ROC sobrepuestas** comparan visualmente la discriminación: entre más se acerque una curva a la esquina superior izquierda, mejor separa solicitudes aprobadas de rechazadas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_logistico <- collect_predictions(ajuste_logistico) %>%\n  mutate(modelo = \"Regresión logística\")\npreds_xgb <- collect_predictions(ajuste_xgb) %>%\n  mutate(modelo = \"XGBoost\")\n\npreds_ambos <- bind_rows(preds_logistico, preds_xgb)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  group_by(modelo) %>%\n  roc_curve(truth = aprobada, .pred_si) %>%\n  autoplot() +\n  labs(title = \"Curvas ROC en la base de prueba\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-26-1.png){width=768}\n:::\n:::\n\n\nLas **matrices de confusión** muestran en qué se equivoca cada modelo (falsos positivos vs. falsos negativos), información que el AUC resume pero no detalla.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_logistico, truth = aprobada, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — Regresión logística\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_mat(preds_xgb, truth = aprobada, estimate = .pred_class) %>%\n  autoplot(type = \"heatmap\") +\n  labs(title = \"Matriz de confusión — XGBoost\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\nLa **gráfica de importancia de variables** (`vip`) ordena los predictores según cuánto contribuyeron a las decisiones de XGBoost. A diferencia de la logística, XGBoost no entrega coeficientes interpretables uno a uno, así que esta gráfica es la principal vía para entender qué factores de riesgo (edad, tabaquismo, IMC, antecedentes) pesan más en la aprobación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_xgb %>%\n  extract_fit_parsnip() %>%\n  vip::vip(num_features = 12) +\n  labs(title = \"Importancia de variables — XGBoost\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\nLas clases están razonablemente balanceadas, así que la métrica de decisión es el **AUC** (mayor es mejor). Ordenamos la tabla por AUC e identificamos al ganador.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final <- metricas_comparacion %>%\n  mutate(across(where(is.numeric), ~ round(., 3))) %>%\n  arrange(desc(roc_auc))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_auc <- round(ganador$roc_auc - perdedor$roc_auc, 3)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo              | accuracy| sensitivity|  spec| roc_auc|\n|:-------------------|--------:|-----------:|-----:|-------:|\n|XGBoost             |    0.768|       0.733| 0.798|   0.849|\n|Regresión logística |    0.536|       0.406| 0.647|   0.561|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: XGBoost.** Obtiene el mayor AUC en la base de prueba (0.849), frente a 0.561 del otro modelo (diferencia de 0.288).\n\n> La ventaja de **XGBoost** es clara (0.288 de AUC), por lo que es la elección recomendada para este problema.\n\nComo las clases están razonablemente balanceadas, el *accuracy* también es informativo aquí; en problemas desbalanceados habría que mirar recall y precision en su lugar. Vale la pena recordar el contraste de fondo: la **regresión logística** ofrece interpretabilidad directa (cada coeficiente indica cómo cambia el log-odds de aprobación, p. ej. ser fumador suele reducirlo), mientras que **XGBoost** capta interacciones entre factores de riesgo y suele predecir mejor, apoyándose en la importancia de variables para interpretar qué pesa más.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}