{
  "hash": "125ab1c08574444ec277fd2ff6e6677d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión: precio de viviendas\"\nsubtitle: \"EJERCICIO DE REGRESIÓN — Regresión lineal vs. random forest\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir el `precio` de una vivienda a partir de sus características físicas y de ubicación. Compararemos dos modelos sobre el mismo flujo de trabajo: una **regresión lineal** (modelo base, interpretable) y un **random forest** (ensamble de árboles por *bagging*, que capta no linealidades e interacciones). El conjunto de datos combina variables numéricas con variables categóricas (colonia, estilo), así que la receta tendrá que codificarlas como variables *dummy*. Recorreremos el flujo completo de `tidymodels`: partición de los datos, receta de preprocesamiento, `workflow()`, validación cruzada, ajuste de hiperparámetros y una evaluación honesta con `last_fit()`. Al final daremos un **veredicto claro** sobre cuál modelo conviene.\n\n## 1. Cargar librerías\n\nAgrupamos todas las librerías al inicio (buena práctica de reproducibilidad). `tidyverse` da el lenguaje de manipulación de datos; `tidymodels` es el marco de modelado; `readxl` lee el archivo de Excel; `ranger` es el motor que ajusta el random forest; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(readxl)\nlibrary(ranger)\n```\n:::\n\n\n`tidymodels_prefer()` resuelve los conflictos de nombres a favor de tidymodels (por ejemplo, que `spec()` sea la de yardstick y no la de otro paquete).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nLos datos vienen en un archivo de Excel, así que los leemos con `read_excel()`. A diferencia de otros conjuntos, aquí no hay una columna identificadora (tipo `id`) que debamos remover. Las variables de texto (como `colonia` y `estilo`) se dejan como están; la receta las convertirá en variables *dummy* más adelante.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Los datos vienen en Excel. No hay columna identificadora que remover.\nviviendas <- read_excel(\"precio_viviendas_2.xlsx\")\n```\n:::\n\n\n`glimpse()` nos da un vistazo rápido a los tipos y valores de cada columna. Conviene fijarse en cuáles son numéricas y cuáles son categóricas (texto).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(viviendas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 800\nColumns: 11\n$ m2_construidos    <dbl> 217, 182, 226, 256, 202, 170, 204, 175, 159, 222, 15…\n$ recamaras         <dbl> 3, 2, 3, 5, 5, 2, 3, 5, 2, 3, 2, 2, 2, 3, 5, 4, 5, 2…\n$ banos             <dbl> 2.8, 2.2, 3.1, 3.6, 3.8, 1.5, 2.8, 3.0, 2.0, 3.3, 2.…\n$ cochera_m2        <dbl> 48.1, 39.5, 43.7, 55.6, 42.2, 31.1, 43.4, 36.6, 33.4…\n$ m2_terreno        <dbl> 146, 353, 274, 216, 187, 141, 193, 169, 106, 347, 16…\n$ anio_construccion <dbl> 2002, 1984, 1984, 1968, 1996, 1990, 2000, 1994, 1970…\n$ colonia           <chr> \"Norte\", \"Poniente\", \"Sur\", \"Poniente\", \"Norte\", \"Su…\n$ estilo            <chr> \"Colonial\", \"Moderno\", NA, \"Colonial\", \"Colonial\", \"…\n$ tiene_alberca     <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\"…\n$ inspeccion        <chr> \"aprobado\", \"aprobado\", \"aprobado\", \"aprobado\", \"apr…\n$ precio            <dbl> 3370190, 3050204, 3797343, 3588065, 3480137, 2654649…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nAntes de modelar conviene entender la variable objetivo y las relaciones entre predictores. Tres revisiones mínimas: la **distribución de la objetivo** (¿hay asimetría o valores extremos?), los **datos faltantes** (¿qué tendremos que imputar?) y la **colinealidad** (¿hay predictores que miden casi lo mismo?).\n\nPrimero, el histograma del precio. Los precios de vivienda suelen tener una cola derecha larga (unas pocas casas muy caras): buscamos si la distribución es aproximadamente simétrica o muy sesgada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviviendas %>%\n  ggplot(aes(x = precio)) +\n  geom_histogram(bins = 30, fill = \"#1e4c7d\", color = \"white\") +\n  labs(title = \"Distribución del precio de las viviendas\",\n       x = \"Precio (MXN)\", y = \"Frecuencia\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n`summary()` resume cada variable y, de paso, nos dice cuántos `NA` tiene cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(viviendas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n m2_construidos    recamaras         banos         cochera_m2   \n Min.   :  4.0   Min.   :1.000   Min.   :1.000   Min.   : 5.50  \n 1st Qu.:138.8   1st Qu.:3.000   1st Qu.:2.400   1st Qu.:29.88  \n Median :179.0   Median :3.000   Median :2.700   Median :37.10  \n Mean   :179.9   Mean   :3.449   Mean   :2.766   Mean   :37.47  \n 3rd Qu.:218.0   3rd Qu.:4.000   3rd Qu.:3.200   3rd Qu.:44.80  \n Max.   :376.0   Max.   :6.000   Max.   :4.800   Max.   :76.30  \n                                 NA's   :14                     \n   m2_terreno     anio_construccion   colonia             estilo         \n Min.   :  78.0   Min.   :1955      Length:800         Length:800        \n 1st Qu.: 186.2   1st Qu.:1971      Class :character   Class :character  \n Median : 238.0   Median :1988      Mode  :character   Mode  :character  \n Mean   : 262.1   Mean   :1987                                           \n 3rd Qu.: 316.0   3rd Qu.:2003                                           \n Max.   :1126.0   Max.   :2020                                           \n NA's   :54       NA's   :37                                             \n tiene_alberca       inspeccion            precio       \n Length:800         Length:800         Min.   : 658884  \n Class :character   Class :character   1st Qu.:2613565  \n Mode  :character   Mode  :character   Median :3084846  \n                                       Mean   :3108479  \n                                       3rd Qu.:3628371  \n                                       Max.   :5806235  \n                                                        \n```\n\n\n:::\n:::\n\n\nContamos los `NA` por columna de forma explícita: esto guía qué pasos de imputación necesitará la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nviviendas %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable          | n_na|\n|:-----------------|----:|\n|m2_terreno        |   54|\n|anio_construccion |   37|\n|estilo            |   34|\n|banos             |   14|\n|m2_construidos    |    0|\n|recamaras         |    0|\n|cochera_m2        |    0|\n|colonia           |    0|\n|tiene_alberca     |    0|\n|inspeccion        |    0|\n|precio            |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación nos deja ver colinealidad entre predictores numéricos (por ejemplo, `m2_construidos` y `m2_terreno` suelen moverse juntas). Si dos variables miden casi lo mismo, la regresión lineal sufre (infla la varianza de los coeficientes); por eso más adelante filtraremos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colinealidad entre las variables numéricas (p. ej. m2_construidos y\n# m2_terreno).\nmatriz_correlacion <- viviendas %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba\n\nDividimos los datos en **entrenamiento** (75%) y **prueba** (25%). La base de prueba se \"guarda en una caja fuerte\": no la tocamos hasta el final, para obtener una estimación honesta del desempeño en datos nuevos. Estratificamos por la objetivo para que ambas particiones cubran rangos de precio parecidos (en regresión, `initial_split` estratifica por cuantiles).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nviviendas_split <- initial_split(viviendas, prop = 0.75, strata = precio)\nviviendas_entrenamiento <- viviendas_split %>% training()\nviviendas_prueba <- viviendas_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(entrenamiento = nrow(viviendas_entrenamiento),\n  prueba = nrow(viviendas_prueba))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nentrenamiento        prueba \n          600           200 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que los dos modelos sean comparables: ambos verán exactamente la misma representación de los datos. Como hay variables categóricas (colonia, estilo, etc.), un paso clave aquí es `step_dummy`, que las convierte en columnas 0/1; sin esa codificación, ni la regresión lineal ni el random forest podrían usarlas.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se *aprenden* solo con el entrenamiento y luego se aplican igual a la prueba (esto evita fuga de información). El orden importa: imputamos los `NA` **primero**, porque pasos como `step_corr` o `step_normalize` no toleran faltantes; normalizamos antes de crear *dummies* para que estas queden en 0/1; y dejamos `step_zv` al final como red de seguridad.\n:::\n\nEl papel de `step_dummy` merece una nota aparte, porque es lo que distingue a este conjunto de datos: tiene variables de texto (colonia, estilo) que ningún modelo numérico puede usar tal cual.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace step_dummy con las variables categóricas?\nVariables como `colonia` o `estilo` son texto, y los modelos solo operan con números. `step_dummy` convierte cada categoría en columnas indicadoras 0/1 (*one-hot* con una categoría de referencia). Así, una `colonia` con 5 valores se vuelve 4 columnas binarias. Es indispensable para la regresión lineal y también lo usamos aquí para el random forest, de modo que **ambos modelos vean exactamente la misma matriz de predictores** y la comparación sea limpia.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Receta única comparable:\n#  1. Imputar numéricos (mediana) y nominales (moda).\n#  2. step_nzv: quitar casi-constantes.\n#  3. step_corr: filtrar colinealidad numérica (umbral 0.85).\n#  4. step_normalize: estandarizar numéricos.\n#  5. step_dummy: codificar colonia, estilo, tiene_alberca, inspeccion.\n#  6. step_zv: por seguridad.\nreceta_viviendas <- recipe(precio ~ ., data = viviendas_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nConviene \"hornear\" la receta una vez para ver cómo quedan las variables tras el preprocesamiento (solo es inspección; el `workflow` lo hará por nosotros después). Fíjate cómo las categóricas se expandieron en varias columnas *dummy*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_viviendas %>%\n  prep(training = viviendas_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 600\nColumns: 12\n$ m2_construidos    <dbl> -0.3388427, -1.6999385, -0.4036567, -1.2786469, -0.8…\n$ recamaras         <dbl> -1.2506089, -1.2506089, -1.2506089, 0.4224465, 0.422…\n$ banos             <dbl> -1.2754060, -1.1136892, -0.6285390, 0.5034781, 0.018…\n$ m2_terreno        <dbl> -1.44018482, 0.81617176, -0.65736723, -0.31661134, -…\n$ anio_construccion <dbl> -0.95412731, 0.64110691, 0.96015375, 0.58793243, 0.4…\n$ precio            <dbl> 2379943, 1731176, 2607709, 2096274, 2576822, 1877924…\n$ colonia_Norte     <dbl> 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…\n$ colonia_Poniente  <dbl> 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0…\n$ colonia_Sur       <dbl> 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…\n$ estilo_Moderno    <dbl> 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1…\n$ estilo_Rustico    <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…\n$ tiene_alberca_si  <dbl> 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nDefinimos los dos modelos con `parsnip`. El primero es la **regresión lineal**: no tiene hiperparámetros que ajustar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_lineal <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nEl segundo es el **random forest**, donde sí ajustaremos dos hiperparámetros (`mtry` y `min_n`). Pedimos `importance = \"impurity\"` al motor para poder graficar después la importancia de variables.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un random forest (bagging)?\nUn **random forest** promedia cientos de árboles, cada uno entrenado sobre una muestra *bootstrap* de los datos y con un subconjunto aleatorio de predictores en cada corte. Promediar muchos árboles ruidosos pero poco sesgados **reduce la varianza** sin aumentar el sesgo, lo que suele dar mejores predicciones que un solo árbol. Ajustamos `mtry` (cuántos predictores se consideran en cada corte) y `min_n` (mínimo de observaciones por nodo); `trees = 500` fija el número de árboles. `tune()` marca `mtry` y `min_n` como \"a determinar por validación cruzada\".\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_rf <- rand_forest(\n    mtry = tune(),\n    min_n = tune(),\n    trees = 500\n  ) %>%\n  set_engine(\"ranger\", importance = \"impurity\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nCada modelo se empaqueta con la **misma** receta en su propio `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos sin que tengamos que recordarlo. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_lineal <- workflow() %>%\n  add_recipe(receta_viviendas) %>%\n  add_model(modelo_lineal)\n\nworkflow_rf <- workflow() %>%\n  add_recipe(receta_viviendas) %>%\n  add_model(modelo_rf)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\nPara comparar los modelos y elegir los hiperparámetros del random forest **sin tocar la prueba**, usamos validación cruzada sobre el entrenamiento.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y evaluamos en el fold restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(viviendas_entrenamiento, v = 5, strata = precio)\n```\n:::\n\n\nDefinimos las métricas de regresión que vigilaremos.\n\n::: {.callout-note collapse=\"true\"}\n## RMSE, MAE y R²\n- **RMSE** (raíz del error cuadrático medio): error típico en las unidades de la objetivo; penaliza más los errores grandes. Es la métrica de decisión.\n- **MAE** (error absoluto medio): error típico, más robusto a valores extremos.\n- **R²**: proporción de la variación de la objetivo que el modelo explica (1 = perfecto; 0 = no mejor que predecir la media).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_regresion <- metric_set(rmse, rsq, mae)\n```\n:::\n\n\nLa regresión lineal **no se tunea**; estimamos su desempeño en CV con `fit_resamples()`. Esto la pone en igualdad de condiciones que el random forest.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (regresión lineal), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el random forest), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_lineal <- workflow_lineal %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_regresion)\n\ncollect_metrics(cv_lineal)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric |.estimator |           mean|  n|       std_err|.config         |\n|:-------|:----------|--------------:|--:|-------------:|:---------------|\n|mae     |standard   | 214696.8877761|  5| 17126.3722536|pre0_mod0_post0 |\n|rmse    |standard   | 270403.3162853|  5| 20936.7601942|pre0_mod0_post0 |\n|rsq     |standard   |      0.8927836|  5|     0.0148171|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara el random forest construimos una grilla de hiperparámetros: combinaciones de `mtry` (entre 2 y 6 predictores por corte) y `min_n` (entre 2 y 40 observaciones por nodo), con `levels = 4` para 4 × 4 = 16 candidatos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrilla_rf <- grid_regular(\n    mtry(range = c(2, 6)),\n    min_n(range = c(2, 40)),\n    levels = 4\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_rf <- workflow_rf %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_rf,\n            metrics = metricas_regresion)\n```\n:::\n\n\nLa siguiente gráfica resume el tuning: muestra el RMSE de validación cruzada según `mtry`, con una línea por valor de `min_n`. Buscamos la combinación con menor RMSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuning_rf %>%\n  collect_metrics() %>%\n  filter(.metric == \"rmse\") %>%\n  ggplot(aes(x = mtry, y = mean, color = factor(min_n))) +\n  geom_line() +\n  geom_point(size = 2) +\n  labs(title = \"RMSE en validación cruzada — random forest\",\n       x = \"mtry (predictores por corte)\", y = \"RMSE promedio\",\n       color = \"min_n\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-22-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_rf <- tuning_rf %>% select_best(metric = \"rmse\")\nmejor_rf\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mtry| min_n|.config          |\n|----:|-----:|:----------------|\n|    6|    14|pre0_mod14_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa regresión lineal ya está lista. Al random forest le **inyectamos** los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_rf_final <- workflow_rf %>%\n  finalize_workflow(mejor_rf)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_lineal <- workflow_lineal %>%\n  last_fit(split = viviendas_split, metrics = metricas_regresion)\n\najuste_rf <- workflow_rf_final %>%\n  last_fit(split = viviendas_split, metrics = metricas_regresion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de **ambos** modelos en la base de prueba en una sola tabla. Esta es la comparación que nos interesa: el desempeño en datos no vistos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_lineal) %>% mutate(modelo = \"Regresión lineal\"),\n    collect_metrics(ajuste_rf) %>% mutate(modelo = \"Random forest\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(rmse)\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |     rmse|       rsq|      mae|\n|:----------------|--------:|---------:|--------:|\n|Regresión lineal | 249816.2| 0.9022170| 200156.0|\n|Random forest    | 293113.5| 0.8636891| 234919.5|\n\n</div>\n:::\n:::\n\n\nPara visualizar la calidad de cada modelo, graficamos los valores reales contra los predichos. La diagonal roja es la predicción perfecta: entre más pegados los puntos a la línea, mejor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_lineal <- collect_predictions(ajuste_lineal) %>%\n  mutate(modelo = \"Regresión lineal\")\npreds_rf <- collect_predictions(ajuste_rf) %>%\n  mutate(modelo = \"Random forest\")\n\npreds_ambos <- bind_rows(preds_lineal, preds_rf)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  ggplot(aes(x = precio, y = .pred)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_abline(color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Valores reales vs. predichos (base de prueba)\",\n       x = \"Precio real (MXN)\", y = \"Precio predicho (MXN)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\nEl gráfico de residuos (real − predicho) contra el valor predicho ayuda a detectar sesgos: buscamos una nube sin patrón alrededor del cero. Un embudo o una curva indicarían que el modelo se equivoca sistemáticamente en algún rango (común en precios: a veces se subestiman las casas más caras).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  mutate(residuo = precio - .pred) %>%\n  ggplot(aes(x = .pred, y = residuo)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_hline(yintercept = 0, color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Residuos vs. valores predichos\",\n       x = \"Precio predicho (MXN)\", y = \"Residuo (real − predicho)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\nUna ventaja del random forest es que nos dice **qué variables pesan más** en sus predicciones. La gráfica de importancia (`vip`) ordena los predictores según cuánto reducen el error al usarse en los cortes de los árboles (importancia por *impurity*, que pedimos al motor con `importance = \"impurity\"`). Las barras más largas son los principales determinantes del precio; suelen aparecer arriba la superficie construida, la ubicación (colonias específicas) y el número de recámaras.\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_rf %>%\n  extract_fit_parsnip() %>%\n  vip::vip(num_features = 12) +\n  labs(title = \"Importancia de variables — random forest\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-30-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordenamos por RMSE (menor es mejor) y medimos la diferencia relativa entre\n# el mejor y el segundo, para juzgar si la ventaja es relevante o marginal.\ntabla_final <- metricas_comparacion %>%\n  arrange(rmse) %>%\n  mutate(rmse = round(rmse, 2),\n         rsq = round(rsq, 3),\n         mae = round(mae, 2))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_rel_pct <- round(100 * (perdedor$rmse - ganador$rmse) / perdedor$rmse, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tabla comparativa final (ordenada del mejor al peor por RMSE)\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |     rmse|   rsq|      mae|\n|:----------------|--------:|-----:|--------:|\n|Regresión lineal | 249816.2| 0.902| 200156.0|\n|Random forest    | 293113.5| 0.864| 234919.5|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión lineal.** Obtiene el menor RMSE en la base de prueba (249816.2 MXN) con un R² de 0.902, frente a 293113.52 MXN del random forest. Su RMSE es **14.8% menor**.\n\n> La ventaja de **Regresión lineal** es relevante (14.8% en RMSE), por lo que es la elección clara para este problema.\n\nRecuerda el balance: la regresión lineal es la más fácil de interpretar (un coeficiente por variable, incluida cada *dummy* de colonia o estilo), mientras que el random forest captura no linealidades e interacciones (por ejemplo, que el valor del terreno dependa de la colonia) a costa de ser una \"caja\" menos transparente; la gráfica de importancia de variables ayuda a abrir un poco esa caja.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}