{
  "hash": "031ebd91a36b031128f33125d6a8fed6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión: contaminación por PM2.5\"\nsubtitle: \"EJERCICIO DE REGRESIÓN — Regresión lineal vs. random forest\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir la concentración diaria de partículas finas (`pm25_ug_m3`, en µg/m³) a partir de variables meteorológicas y de tráfico. Compararemos dos modelos sobre el mismo flujo de trabajo: una **regresión lineal** (modelo base, interpretable) y un **random forest** (ensamble de árboles por *bagging*, que capta no linealidades e interacciones). Recorreremos el flujo completo de `tidymodels`: partición de los datos, receta de preprocesamiento, `workflow()`, validación cruzada, ajuste de hiperparámetros y una evaluación honesta con `last_fit()`. Al final daremos un **veredicto claro** sobre cuál modelo conviene.\n\n## 1. Cargar librerías\n\nAgrupamos todas las librerías al inicio (buena práctica de reproducibilidad). `tidyverse` da el lenguaje de manipulación de datos; `tidymodels` es el marco de modelado; `ranger` es el motor rápido que ajusta el random forest; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(ranger)\n```\n:::\n\n\n`tidymodels_prefer()` resuelve los conflictos de nombres a favor de tidymodels (por ejemplo, que `spec()` sea la de yardstick y no la de otro paquete).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nLeemos el CSV y removemos `dia`: es un índice temporal y la estacionalidad ya queda capturada por la variable categórica `estacion`, que la receta convertirá en variables *dummy* más adelante.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quitamos la columna de fecha (dia): es un índice temporal y la estacionalidad\n# ya queda capturada por la variable categórica estacion. estacion se convierte\n# en dummies en la receta.\naire <- read_csv(\"datos.csv\") %>%\n  select(-dia)\n```\n:::\n\n\n`glimpse()` nos da un vistazo rápido a tipos y valores de cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(aire)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 520\nColumns: 12\n$ estacion           <chr> \"invierno\", \"invierno\", \"invierno\", \"invierno\", \"in…\n$ indice_trafico     <dbl> 70.28637, 64.39458, 73.79904, 69.27240, 68.92196, 5…\n$ viento_kmh         <dbl> 12.384459, 5.896942, 16.404255, 2.000000, 7.483716,…\n$ humedad            <dbl> 83.57585, 45.13795, 42.91317, 65.83004, 63.64328, 5…\n$ temperatura_c      <dbl> 22.19105, 27.38995, 24.57989, 20.08605, 16.17431, 2…\n$ velocidad_promedio <dbl> 30.57398, 34.94523, 27.80300, 36.02605, 30.14430, 3…\n$ no2_ppb            <dbl> 38.47775, 35.79477, 38.35911, 34.12989, 38.18760, 2…\n$ co_ppm             <dbl> 1.0040996, 0.9001051, 1.0941563, 1.2070546, 1.08223…\n$ entregas_urbanas   <dbl> 2245.405, 2038.786, 2290.453, 2127.329, 2277.316, 1…\n$ lluvia_mm          <dbl> 2.0952860, 3.4105318, 1.0645180, 2.2519168, 5.58305…\n$ inversion_termica  <dbl> 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, …\n$ pm25_ug_m3         <dbl> 51.28397, 42.85975, 37.47442, 51.04379, 48.48263, 1…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nAntes de modelar conviene entender la variable objetivo y las relaciones entre predictores. Tres revisiones mínimas: la **distribución de la objetivo** (¿hay asimetría o valores extremos?), los **datos faltantes** (¿qué tendremos que imputar?) y la **colinealidad** (¿hay predictores que miden casi lo mismo?).\n\nPrimero, el histograma de PM2.5. Buscamos si la distribución es aproximadamente simétrica (cómoda para la regresión lineal) o muy sesgada hacia valores altos (típico en contaminación, por episodios de mala calidad del aire).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Distribución de la objetivo.\naire %>%\n  ggplot(aes(x = pm25_ug_m3)) +\n  geom_histogram(bins = 30, fill = \"#1e4c7d\", color = \"white\") +\n  labs(title = \"Distribución de PM2.5\",\n       x = \"PM2.5 (µg/m³)\", y = \"Frecuencia\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n`summary()` resume cada variable y, de paso, nos dice cuántos `NA` tiene cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aire)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   estacion         indice_trafico     viento_kmh        humedad     \n Length:520         Min.   : 25.90   Min.   : 2.000   Min.   :24.72  \n Class :character   1st Qu.: 62.16   1st Qu.: 7.825   1st Qu.:52.67  \n Mode  :character   Median : 70.14   Median :10.368   Median :62.97  \n                    Mean   : 70.06   Mean   :10.499   Mean   :62.68  \n                    3rd Qu.: 78.48   3rd Qu.:13.166   3rd Qu.:72.19  \n                    Max.   :104.43   Max.   :21.908   Max.   :95.00  \n temperatura_c    velocidad_promedio    no2_ppb          co_ppm      \n Min.   : 7.272   Min.   :12.77      Min.   :15.38   Min.   :0.5601  \n 1st Qu.:18.242   1st Qu.:24.90      1st Qu.:32.31   1st Qu.:0.9177  \n Median :21.577   Median :28.24      Median :37.29   Median :1.0160  \n Mean   :21.256   Mean   :28.21      Mean   :37.34   Mean   :1.0234  \n 3rd Qu.:24.468   3rd Qu.:31.67      3rd Qu.:42.18   3rd Qu.:1.1365  \n Max.   :34.899   Max.   :43.34      Max.   :60.00   Max.   :1.5272  \n entregas_urbanas   lluvia_mm        inversion_termica   pm25_ug_m3    \n Min.   :1581     Min.   : 0.02573   Min.   :0.0000    Min.   : 8.166  \n 1st Qu.:1984     1st Qu.: 0.98202   1st Qu.:0.0000    1st Qu.:27.948  \n Median :2125     Median : 2.14794   Median :0.0000    Median :33.961  \n Mean   :2120     Mean   : 2.91803   Mean   :0.1731    Mean   :34.079  \n 3rd Qu.:2258     3rd Qu.: 4.15855   3rd Qu.:0.0000    3rd Qu.:40.312  \n Max.   :2698     Max.   :18.21519   Max.   :1.0000    Max.   :58.670  \n```\n\n\n:::\n:::\n\n\nContamos los `NA` por columna de forma explícita: esto guía qué pasos de imputación necesitará la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naire %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable           | n_na|\n|:------------------|----:|\n|estacion           |    0|\n|indice_trafico     |    0|\n|viento_kmh         |    0|\n|humedad            |    0|\n|temperatura_c      |    0|\n|velocidad_promedio |    0|\n|no2_ppb            |    0|\n|co_ppm             |    0|\n|entregas_urbanas   |    0|\n|lluvia_mm          |    0|\n|inversion_termica  |    0|\n|pm25_ug_m3         |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación nos deja ver colinealidad entre predictores numéricos. En contaminación urbana es esperable que el tráfico, el NO2 y el CO se muevan juntos (comparten la misma fuente: la combustión vehicular). Si dos variables miden casi lo mismo, la regresión lineal sufre (infla la varianza de los coeficientes); por eso más adelante filtraremos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Colinealidad: el tráfico, el NO2 y el CO suelen moverse juntos.\nmatriz_correlacion <- aire %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", tl.cex = 0.7)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-9-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba\n\nDividimos los datos en **entrenamiento** (75%) y **prueba** (25%). La base de prueba se \"guarda en una caja fuerte\": no la tocamos hasta el final, para obtener una estimación honesta del desempeño en datos nuevos. Estratificamos por la objetivo para que ambas particiones cubran rangos de PM2.5 parecidos (en regresión, `initial_split` estratifica por cuantiles).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\naire_split <- initial_split(aire, prop = 0.75, strata = pm25_ug_m3)\naire_entrenamiento <- aire_split %>% training()\naire_prueba <- aire_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(entrenamiento = nrow(aire_entrenamiento), prueba = nrow(aire_prueba))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nentrenamiento        prueba \n          388           132 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que los dos modelos sean comparables: ambos verán exactamente la misma representación de los datos.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se *aprenden* solo con el entrenamiento y luego se aplican igual a la prueba (esto evita fuga de información). El orden importa: imputamos los `NA` **primero**, porque pasos como `step_corr` o `step_normalize` no toleran faltantes; normalizamos antes de crear *dummies* para que estas queden en 0/1; y dejamos `step_zv` al final como red de seguridad.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Una sola receta comparable para ambos modelos:\n#  1. Imputar NAs numéricos (mediana) y nominales (moda).\n#  2. step_nzv: quitar casi-constantes.\n#  3. step_corr: filtrar colinealidad numérica (umbral 0.85).\n#  4. step_normalize: estandarizar numéricos (escala común).\n#  5. step_dummy: codificar estacion.\n#  6. step_zv: por seguridad.\nreceta_aire <- recipe(pm25_ug_m3 ~ ., data = aire_entrenamiento) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nConviene \"hornear\" la receta una vez para ver cómo quedan las variables tras el preprocesamiento (solo es inspección; el `workflow` lo hará por nosotros después).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_aire %>%\n  prep(training = aire_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 388\nColumns: 13\n$ viento_kmh         <dbl> 1.28879798, 1.88195110, 0.27768663, 1.94052102, -0.…\n$ humedad            <dbl> -0.91673919, 0.80477532, -0.82724648, -1.30065781, …\n$ temperatura_c      <dbl> 0.56797627, 2.10903861, 1.54236840, 0.42977438, 0.5…\n$ velocidad_promedio <dbl> 1.89035873, 0.88496130, 0.38537882, 0.74511919, 0.7…\n$ no2_ppb            <dbl> -1.13577637, -2.02577001, -2.32632731, -0.51423795,…\n$ co_ppm             <dbl> -1.87125751, -2.22551110, -1.15618250, 0.71706847, …\n$ entregas_urbanas   <dbl> -0.85543180, -0.95753911, -1.38394549, 0.37107362, …\n$ lluvia_mm          <dbl> 0.17705461, 0.11162626, -0.57086587, -1.08593161, -…\n$ inversion_termica  <dbl> -0.4480176, -0.4480176, -0.4480176, -0.4480176, -0.…\n$ pm25_ug_m3         <dbl> 17.86102, 10.69914, 23.50951, 19.98504, 24.80237, 2…\n$ estacion_otono     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ estacion_primavera <dbl> 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ estacion_verano    <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nDefinimos los dos modelos con `parsnip`. El primero es la **regresión lineal**: no tiene hiperparámetros que ajustar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelo 1: regresión lineal (sin hiperparámetros).\nmodelo_lineal <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nEl segundo es el **random forest**, donde sí ajustaremos dos hiperparámetros (`mtry` y `min_n`).\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un random forest (bagging)?\nUn **random forest** promedia cientos de árboles, cada uno entrenado sobre una muestra *bootstrap* y con un subconjunto aleatorio de predictores en cada corte. Promediar muchos árboles ruidosos pero poco sesgados **reduce la varianza** sin aumentar el sesgo, y de paso capta no linealidades e interacciones que la regresión lineal no ve. Ajustamos `mtry` (cuántos predictores se consideran en cada corte) y `min_n` (mínimo de observaciones por nodo); `tune()` marca esos valores como \"a determinar por validación cruzada\". Fijamos `trees = 500` (suficiente para que la estimación sea estable) e `importance = \"impurity\"` para poder inspeccionar después qué variables pesan más.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelo 2: random forest (ranger). Tuneamos:\n#  - mtry: cuántos predictores se consideran en cada corte.\n#  - min_n: mínimo de observaciones por nodo.\n# Fijamos trees = 500 (estable). importance = \"impurity\" para inspeccionar\n# después qué variables pesan más.\nmodelo_rf <- rand_forest(\n    mtry = tune(),\n    min_n = tune(),\n    trees = 500\n  ) %>%\n  set_engine(\"ranger\", importance = \"impurity\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nCada modelo se empaqueta con la **misma** receta en su propio `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos sin que tengamos que recordarlo. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_lineal <- workflow() %>%\n  add_recipe(receta_aire) %>%\n  add_model(modelo_lineal)\n\nworkflow_rf <- workflow() %>%\n  add_recipe(receta_aire) %>%\n  add_model(modelo_rf)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\nPara comparar los modelos y elegir los hiperparámetros del random forest **sin tocar la prueba**, usamos validación cruzada sobre el entrenamiento.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y evaluamos en el fold restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(aire_entrenamiento, v = 5, strata = pm25_ug_m3)\n```\n:::\n\n\nDefinimos las métricas de regresión que vigilaremos.\n\n::: {.callout-note collapse=\"true\"}\n## RMSE, MAE y R²\n- **RMSE** (raíz del error cuadrático medio): error típico en las unidades de la objetivo (aquí, µg/m³); penaliza más los errores grandes. Es la métrica de decisión.\n- **MAE** (error absoluto medio): error típico, más robusto a valores extremos.\n- **R²**: proporción de la variación de la objetivo que el modelo explica (1 = perfecto; 0 = no mejor que predecir la media).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_regresion <- metric_set(rmse, rsq, mae)\n```\n:::\n\n\nLa regresión lineal **no se tunea**; estimamos su desempeño en CV con `fit_resamples()`. Esto la pone en igualdad de condiciones que el random forest.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (regresión lineal), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (el random forest), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regresión lineal: desempeño en CV con fit_resamples().\nset.seed(2026)\ncv_lineal <- workflow_lineal %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_regresion)\n\ncollect_metrics(cv_lineal)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric |.estimator |      mean|  n|   std_err|.config         |\n|:-------|:----------|---------:|--:|---------:|:---------------|\n|mae     |standard   | 4.0294345|  5| 0.1175845|pre0_mod0_post0 |\n|rmse    |standard   | 5.0003144|  5| 0.1310553|pre0_mod0_post0 |\n|rsq     |standard   | 0.6688999|  5| 0.0148362|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara el random forest construimos una grilla de hiperparámetros: combinaciones de `mtry` (2 a 6 predictores por corte) y `min_n` (2 a 40 observaciones por nodo). Fijamos rangos explícitos para `mtry` porque su límite superior depende del número de predictores y conviene acotarlo a mano (`levels = 4` da 4 × 4 = 16 candidatos).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grilla del random forest. Fijamos rangos explícitos de mtry y min_n para\n# evitar dejar el límite superior de mtry sin definir.\ngrilla_rf <- grid_regular(\n    mtry(range = c(2, 6)),\n    min_n(range = c(2, 40)),\n    levels = 4\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_rf <- workflow_rf %>%\n  tune_grid(resamples = folds_cv,\n            grid = grilla_rf,\n            metrics = metricas_regresion)\n```\n:::\n\n\nLa siguiente gráfica resume el tuning: muestra el RMSE de validación cruzada según `mtry`, con una línea por nivel de `min_n`. Buscamos la combinación con menor RMSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# RMSE en CV según mtry, por nivel de min_n.\ntuning_rf %>%\n  collect_metrics() %>%\n  filter(.metric == \"rmse\") %>%\n  ggplot(aes(x = mtry, y = mean, color = factor(min_n))) +\n  geom_line() +\n  geom_point(size = 2) +\n  labs(title = \"RMSE en validación cruzada — random forest\",\n       x = \"mtry (predictores por corte)\", y = \"RMSE promedio\",\n       color = \"min_n\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-22-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_rf <- tuning_rf %>% select_best(metric = \"rmse\")\nmejor_rf\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mtry| min_n|.config          |\n|----:|-----:|:----------------|\n|    6|    14|pre0_mod14_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa regresión lineal ya está lista. Al random forest le **inyectamos** los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_rf_final <- workflow_rf %>%\n  finalize_workflow(mejor_rf)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_lineal <- workflow_lineal %>%\n  last_fit(split = aire_split, metrics = metricas_regresion)\n\najuste_rf <- workflow_rf_final %>%\n  last_fit(split = aire_split, metrics = metricas_regresion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas de **ambos** modelos en la base de prueba en una sola tabla. Esta es la comparación que nos interesa: el desempeño en datos no vistos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmetricas_comparacion <- bind_rows(\n    collect_metrics(ajuste_lineal) %>% mutate(modelo = \"Regresión lineal\"),\n    collect_metrics(ajuste_rf) %>% mutate(modelo = \"Random forest\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(rmse)\n\nmetricas_comparacion\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |     rmse|       rsq|      mae|\n|:----------------|--------:|---------:|--------:|\n|Regresión lineal | 5.435880| 0.5873664| 4.395871|\n|Random forest    | 6.048769| 0.5013259| 4.729172|\n\n</div>\n:::\n:::\n\n\nPara visualizar la calidad de cada modelo, graficamos los valores reales contra los predichos. La diagonal roja es la predicción perfecta: entre más pegados los puntos a la línea, mejor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_lineal <- collect_predictions(ajuste_lineal) %>%\n  mutate(modelo = \"Regresión lineal\")\npreds_rf <- collect_predictions(ajuste_rf) %>%\n  mutate(modelo = \"Random forest\")\n\npreds_ambos <- bind_rows(preds_lineal, preds_rf)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  ggplot(aes(x = pm25_ug_m3, y = .pred)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_abline(color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Valores reales vs. predichos (base de prueba)\",\n       x = \"PM2.5 real (µg/m³)\", y = \"PM2.5 predicho (µg/m³)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-28-1.png){width=768}\n:::\n:::\n\n\nEl gráfico de residuos (real − predicho) contra el valor predicho ayuda a detectar sesgos: buscamos una nube sin patrón alrededor del cero. Un embudo o una curva indicarían que el modelo se equivoca sistemáticamente en algún rango (por ejemplo, subestimar los días de mayor contaminación).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds_ambos %>%\n  mutate(residuo = pm25_ug_m3 - .pred) %>%\n  ggplot(aes(x = .pred, y = residuo)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_hline(yintercept = 0, color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Residuos vs. valores predichos\",\n       x = \"PM2.5 predicho (µg/m³)\", y = \"Residuo (real − predicho)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\nUna ventaja del random forest sobre un solo árbol es que, aunque es un modelo \"de caja negra\", podemos recuperar algo de interpretabilidad midiendo la **importancia de cada variable**. La gráfica siguiente ordena los predictores por cuánto reducen la impureza (el error) a lo largo de todos los árboles del bosque: las barras más largas son las variables que más contribuyen a la predicción de PM2.5. Esperamos ver arriba los predictores de combustión y tráfico (NO2, CO, intensidad de tráfico) y las variables meteorológicas que dispersan o concentran las partículas (viento, inversión térmica).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importancia de variables del random forest: qué predictores pesan más.\najuste_rf %>%\n  extract_fit_parsnip() %>%\n  vip::vip(num_features = 12) +\n  labs(title = \"Importancia de variables — random forest\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-30-1.png){width=768}\n:::\n:::\n\n\n## Veredicto: ¿cuál es el mejor modelo?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordenamos por RMSE (menor es mejor) y medimos la diferencia relativa entre\n# el mejor y el segundo, para juzgar si la ventaja es relevante o marginal.\ntabla_final <- metricas_comparacion %>%\n  arrange(rmse) %>%\n  mutate(rmse = round(rmse, 2),\n         rsq = round(rsq, 3),\n         mae = round(mae, 2))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_rel_pct <- round(100 * (perdedor$rmse - ganador$rmse) / perdedor$rmse, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tabla comparativa final (ordenada del mejor al peor por RMSE)\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           | rmse|   rsq|  mae|\n|:----------------|----:|-----:|----:|\n|Regresión lineal | 5.44| 0.587| 4.40|\n|Random forest    | 6.05| 0.501| 4.73|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión lineal.** Obtiene el menor RMSE en la base de prueba (5.44 µg/m³) con un R² de 0.587, frente a 6.05 µg/m³ del random forest. Su RMSE es **10.1% menor**.\n\n> La ventaja de **Regresión lineal** es relevante (10.1% en RMSE), por lo que es la elección clara para este problema.\n\nRecuerda que la regresión lineal es la más fácil de interpretar (un coeficiente por variable), mientras que el random forest promedia cientos de árboles sobre muestras *bootstrap*: reduce la varianza y captura no linealidades e interacciones (por ejemplo, el efecto del viento según haya o no inversión térmica), normalmente a costa de interpretabilidad. La gráfica de importancia de variables ayuda a recuperar parte de esa interpretabilidad perdida, mostrando qué predictores impulsan la predicción de PM2.5.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}