{
  "hash": "71b6260f49144fa395bcd273ceeafa35",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión: costo médico anual (objetivo sesgada)\"\nsubtitle: \"EJERCICIO DE REGRESIÓN — Regresión lineal vs. XGBoost (con log de la objetivo)\"\nauthor: \"Jorge Juvenal Campos Ferreira — TC2001B.601\"\nlang: es\ndate: today\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\n```\n:::\n\n\n**Objetivo.** Predecir el `costo_anual_mxn` de un paciente a partir de su perfil demográfico, de estilo de vida y de uso de servicios. La variable objetivo está **sesgada a la derecha** (una cola larga de pocos pacientes con costos muy altos), por lo que la modelamos en **escala logarítmica**: el logaritmo comprime la cola, estabiliza la varianza y convierte relaciones multiplicativas en relaciones lineales, que es justo lo que la regresión lineal supone. Compararemos una **regresión lineal** (modelo base, interpretable) con **XGBoost** (boosting de árboles, alto poder predictivo). Recorreremos el flujo completo de `tidymodels`: partición de los datos, receta de preprocesamiento, `workflow()`, validación cruzada, ajuste de hiperparámetros y una evaluación honesta con `last_fit()`. Como el modelo trabaja en log, reportaremos el error **en escala log** y, sobre todo, **en pesos** (exponenciando), que es el error que de verdad interpreta el negocio. Al final daremos un **veredicto claro** sobre cuál modelo conviene.\n\n## 1. Cargar librerías\n\nAgrupamos todas las librerías al inicio (buena práctica de reproducibilidad). `tidyverse` da el lenguaje de manipulación de datos; `tidymodels` es el marco de modelado; `xgboost` es el motor que ajusta el modelo de boosting; `corrplot` dibuja la matriz de correlación.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(corrplot)\nlibrary(xgboost)\n```\n:::\n\n\n`tidymodels_prefer()` resuelve los conflictos de nombres a favor de tidymodels (por ejemplo, que ciertas funciones genéricas sean las de tidymodels y no las de otro paquete).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidymodels::tidymodels_prefer()\n```\n:::\n\n\n## 2. Cargar los datos\n\nLeemos el CSV y removemos `id_paciente`: es un identificador único por fila, no aporta poder predictivo y, si lo dejáramos, solo metería ruido. Las variables de texto (`sexo`, `fumador`, `region`) las dejamos como están; la receta las convertirá en variables *dummy* más adelante.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Removemos id_paciente (identificador). sexo, fumador y region son categóricas\n# (se vuelven dummies en la receta).\ncostos <- read_csv(\"datos.csv\") %>%\n  select(-id_paciente)\n```\n:::\n\n\n`glimpse()` nos da un vistazo rápido a tipos y valores de cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(costos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,050\nColumns: 9\n$ edad                     <dbl> 65, 69, 59, 38, 37, 31, 41, 36, 18, 30, 46, 2…\n$ sexo                     <chr> \"F\", \"M\", \"M\", \"M\", \"F\", \"M\", \"F\", \"F\", \"F\", …\n$ imc                      <dbl> 28.0, 29.5, 31.0, 21.6, 13.8, 33.9, 33.0, 22.…\n$ hijos                    <dbl> 1, 2, 1, 0, 2, 0, 0, 0, 0, 1, 2, 3, 0, 0, 4, …\n$ fumador                  <chr> \"no\", \"no\", \"no\", \"si\", \"no\", \"no\", \"no\", \"si…\n$ region                   <chr> \"bajio\", \"centro\", \"sur\", \"bajio\", \"centro\", …\n$ actividad_fisica_hrs_sem <dbl> 1.8, 1.2, 0.0, 0.1, 3.8, 4.9, 3.0, 3.0, 5.3, …\n$ num_consultas_anio       <dbl> 3, 5, 2, 1, 3, 1, 5, 2, 5, 2, 3, 1, 4, 0, 2, …\n$ costo_anual_mxn          <dbl> 66503, 98463, 41598, 47506, 15643, 38896, 417…\n```\n\n\n:::\n:::\n\n\n## 3. Explorar los datos\n\nAntes de modelar conviene entender la variable objetivo y las relaciones entre predictores. Empezamos por la distribución del costo en su **escala original**: esperamos una clara asimetría a la derecha, con la media arrastrada por encima de la mediana por unos pocos pacientes muy caros.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# La objetivo en su escala original: clara cola a la derecha (media > mediana).\ncostos %>%\n  ggplot(aes(x = costo_anual_mxn)) +\n  geom_histogram(bins = 30, fill = \"#1e4c7d\", color = \"white\") +\n  labs(title = \"Costo anual en pesos (escala original, sesgada)\",\n       x = \"Costo anual (MXN)\", y = \"Frecuencia\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\nAhora la misma variable en **escala logarítmica**. Si la transformación funciona, el histograma se ve mucho más simétrico (casi acampanado): esa simetría es lo que facilita el modelado lineal. Esta es la evidencia visual que justifica aplicar `step_log()` a la objetivo en la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# La misma objetivo en escala logarítmica: se simetriza, lo que facilita el\n# modelado. Por eso aplicaremos step_log() en la receta.\ncostos %>%\n  ggplot(aes(x = log(costo_anual_mxn))) +\n  geom_histogram(bins = 30, fill = \"#1a7a3a\", color = \"white\") +\n  labs(title = \"Costo anual en escala logarítmica (simétrica)\",\n       x = \"log(costo anual)\", y = \"Frecuencia\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n`summary()` resume cada variable y, de paso, nos dice cuántos `NA` tiene cada columna.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(costos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      edad           sexo                imc            hijos     \n Min.   :18.00   Length:1050        Min.   :13.20   Min.   :0.00  \n 1st Qu.:31.00   Class :character   1st Qu.:24.30   1st Qu.:0.00  \n Median :44.00   Mode  :character   Median :28.00   Median :1.00  \n Mean   :43.85                      Mean   :27.95   Mean   :1.07  \n 3rd Qu.:56.75                      3rd Qu.:31.70   3rd Qu.:2.00  \n Max.   :70.00                      Max.   :46.40   Max.   :7.00  \n                                    NA's   :42                    \n   fumador             region          actividad_fisica_hrs_sem\n Length:1050        Length:1050        Min.   : 0.000          \n Class :character   Class :character   1st Qu.: 1.700          \n Mode  :character   Mode  :character   Median : 3.000          \n                                       Mean   : 3.037          \n                                       3rd Qu.: 4.300          \n                                       Max.   :10.000          \n                                                               \n num_consultas_anio costo_anual_mxn \n Min.   :0.000      Min.   :  6676  \n 1st Qu.:1.000      1st Qu.: 22845  \n Median :2.000      Median : 37860  \n Mean   :2.523      Mean   : 50086  \n 3rd Qu.:4.000      3rd Qu.: 61469  \n Max.   :9.000      Max.   :317728  \n                                    \n```\n\n\n:::\n:::\n\n\nContamos los `NA` por columna de forma explícita: esto guía qué pasos de imputación necesitará la receta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncostos %>%\n  summarise(across(everything(), ~ sum(is.na(.)))) %>%\n  pivot_longer(everything(), names_to = \"variable\", values_to = \"n_na\") %>%\n  arrange(desc(n_na))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|variable                 | n_na|\n|:------------------------|----:|\n|imc                      |   42|\n|edad                     |    0|\n|sexo                     |    0|\n|hijos                    |    0|\n|fumador                  |    0|\n|region                   |    0|\n|actividad_fisica_hrs_sem |    0|\n|num_consultas_anio       |    0|\n|costo_anual_mxn          |    0|\n\n</div>\n:::\n:::\n\n\nLa matriz de correlación nos deja ver colinealidad entre predictores numéricos (por ejemplo, edad e IMC podrían moverse juntos). Si dos variables miden casi lo mismo, la regresión lineal sufre (infla la varianza de los coeficientes); por eso más adelante filtraremos con `step_corr()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatriz_correlacion <- costos %>%\n  select(where(is.numeric)) %>%\n  drop_na() %>%\n  cor() %>%\n  round(2)\n\nmatriz_correlacion %>%\n  corrplot(method = \"circle\", addCoef.col = \"black\", tl.cex = 0.8)\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-10-1.png){width=768}\n:::\n:::\n\n\n## 4. Partición entrenamiento / prueba\n\nDividimos los datos en **entrenamiento** (75%) y **prueba** (25%). La base de prueba se \"guarda en una caja fuerte\": no la tocamos hasta el final, para obtener una estimación honesta del desempeño en datos nuevos. Estratificamos por la objetivo para que ambas particiones cubran rangos de costo parecidos (en regresión, `initial_split` estratifica por cuantiles).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncostos_split <- initial_split(costos, prop = 0.75, strata = costo_anual_mxn)\ncostos_entrenamiento <- costos_split %>% training()\ncostos_prueba <- costos_split %>% testing()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(entrenamiento = nrow(costos_entrenamiento),\n  prueba = nrow(costos_prueba))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nentrenamiento        prueba \n          786           264 \n```\n\n\n:::\n:::\n\n\n## 5. Receta de preprocesamiento (compartida por ambos modelos)\n\nUsamos **una sola receta** para que los dos modelos sean comparables: ambos verán exactamente la misma representación de los datos. El primer paso es el más importante de este ejercicio: `step_log()` sobre la objetivo. Al modelar `log(costo)` en lugar de `costo`, estabilizamos la varianza y linealizamos las relaciones multiplicativas; todo el modelado ocurre entonces en escala log y solo al final reconvertimos a pesos.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es una receta y por qué importa el orden de los pasos?\nUna **receta** (`recipe`) encadena pasos de preprocesamiento (`step_*`) que se *aprenden* solo con el entrenamiento y luego se aplican igual a la prueba (esto evita fuga de información). El orden importa: imputamos los `NA` **primero**, porque pasos como `step_corr` o `step_normalize` no toleran faltantes; normalizamos antes de crear *dummies* para que estas queden en 0/1; y dejamos `step_zv` al final como red de seguridad. Aquí el `step_log()` de la objetivo va al inicio para que toda la evaluación posterior se haga en escala logarítmica.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Paso clave: step_log() sobre la objetivo, PRIMERO, para modelar log(costo).\n# Esto estabiliza la varianza y linealiza relaciones multiplicativas. Luego el\n# preprocesamiento usual de los predictores. step_normalize solo toca\n# predictores (no la objetivo).\nreceta_costos <- recipe(costo_anual_mxn ~ ., data = costos_entrenamiento) %>%\n  step_log(costo_anual_mxn, base = exp(1)) %>%\n  step_impute_median(all_numeric_predictors()) %>%\n  step_impute_mode(all_nominal_predictors()) %>%\n  step_nzv(all_predictors()) %>%\n  step_corr(all_numeric_predictors(), threshold = 0.85) %>%\n  step_normalize(all_numeric_predictors()) %>%\n  step_dummy(all_nominal_predictors()) %>%\n  step_zv(all_predictors())\n```\n:::\n\n\nConviene \"hornear\" la receta una vez para ver cómo quedan las variables tras el preprocesamiento (solo es inspección; el `workflow` lo hará por nosotros después). Nota que `costo_anual_mxn` ya aparece en escala log.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreceta_costos %>%\n  prep(training = costos_entrenamiento) %>%\n  bake(new_data = NULL) %>%\n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 786\nColumns: 11\n$ edad                     <dbl> -0.43611168, -0.50423246, -0.91295715, -0.572…\n$ imc                      <dbl> -2.537879334, -0.940711292, 1.015370918, -1.4…\n$ hijos                    <dbl> 0.93290937, -1.07055173, -0.06882118, 2.93637…\n$ actividad_fisica_hrs_sem <dbl> 0.40068441, -0.03363787, -1.17373387, 1.21503…\n$ num_consultas_anio       <dbl> 0.3048820, -0.3240871, -0.3240871, -0.3240871…\n$ costo_anual_mxn          <dbl> 9.657779, 9.786504, 9.921868, 9.682030, 9.217…\n$ sexo_M                   <dbl> 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, …\n$ fumador_si               <dbl> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ region_centro            <dbl> 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, …\n$ region_norte             <dbl> 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, …\n$ region_sur               <dbl> 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, …\n```\n\n\n:::\n:::\n\n\n## 6. Especificación de los modelos\n\nDefinimos los dos modelos con `parsnip`. El primero es la **regresión lineal**: no tiene hiperparámetros que ajustar. Sobre el log de la objetivo equivale a un modelo multiplicativo en pesos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_lineal <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nEl segundo es **XGBoost**, donde sí ajustaremos varios hiperparámetros.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es XGBoost (boosting)?\n**XGBoost** construye árboles en **secuencia**: cada árbol nuevo corrige los errores del conjunto anterior. El boosting reduce sobre todo el **sesgo** y suele dar el mejor desempeño predictivo, a costa de más hiperparámetros y mayor riesgo de sobreajuste. Aquí fijamos `trees = 500` y ajustamos por validación cruzada `tree_depth` (profundidad de cada árbol), `learn_rate` (cuánto aporta cada árbol) y `loss_reduction` (ganancia mínima para abrir un nodo). `tune()` marca esos valores como \"a determinar\".\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_xgb <- boost_tree(\n    trees = 500,\n    tree_depth = tune(),\n    learn_rate = tune(),\n    loss_reduction = tune()\n  ) %>%\n  set_engine(\"xgboost\") %>%\n  set_mode(\"regression\")\n```\n:::\n\n\nCada modelo se empaqueta con la **misma** receta en su propio `workflow`.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es un workflow?\nUn **workflow** empaqueta en un solo objeto la receta de preprocesamiento y el modelo. Al hacer `fit()` aplica internamente `prep` + `bake` + `fit`, y al `predict()` repite el mismo preprocesamiento sobre los datos nuevos sin que tengamos que recordarlo. Es la pieza estándar para validación cruzada y tuning.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_lineal <- workflow() %>%\n  add_recipe(receta_costos) %>%\n  add_model(modelo_lineal)\n\nworkflow_xgb <- workflow() %>%\n  add_recipe(receta_costos) %>%\n  add_model(modelo_xgb)\n```\n:::\n\n\n## 7. Validación cruzada y tuning de hiperparámetros\n\nPara comparar los modelos y elegir los hiperparámetros de XGBoost **sin tocar la prueba**, usamos validación cruzada sobre el entrenamiento.\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué es la validación cruzada (k-fold)?\nPartimos el entrenamiento en `v` partes (folds) del mismo tamaño. En cada ronda entrenamos con `v − 1` folds y evaluamos en el fold restante, rotando cuál se deja fuera; luego promediamos el desempeño. Así estimamos qué tan bien generaliza el modelo **usando solo el entrenamiento**, y reservamos la prueba para el final.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nfolds_cv <- vfold_cv(costos_entrenamiento, v = 5, strata = costo_anual_mxn)\n```\n:::\n\n\nDefinimos las métricas de regresión que vigilaremos. Un detalle crucial: como la objetivo está en escala log, **estas métricas quedan en escala log**, no en pesos. Las reconvertiremos a pesos en la sección 10.\n\n::: {.callout-note collapse=\"true\"}\n## RMSE, MAE y R²\n- **RMSE** (raíz del error cuadrático medio): error típico en las unidades de la objetivo; penaliza más los errores grandes. Es la métrica de decisión.\n- **MAE** (error absoluto medio): error típico, más robusto a valores extremos.\n- **R²**: proporción de la variación de la objetivo que el modelo explica (1 = perfecto; 0 = no mejor que predecir la media).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# OJO: como la objetivo está en escala log, estas métricas (RMSE, MAE) quedan\n# en escala log. Las reconvertimos a pesos al final.\nmetricas_regresion <- metric_set(rmse, rsq, mae)\n```\n:::\n\n\nLa regresión lineal **no se tunea**; estimamos su desempeño en CV con `fit_resamples()`. Esto la pone en igualdad de condiciones que XGBoost.\n\n::: {.callout-note collapse=\"true\"}\n## fit_resamples() vs. tune_grid()\nCuando un modelo **no** tiene hiperparámetros que ajustar (regresión lineal), `fit_resamples()` solo lo evalúa en cada fold. Cuando **sí** los tiene (XGBoost), `tune_grid()` prueba varias combinaciones de hiperparámetros en la validación cruzada y nos deja elegir la mejor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ncv_lineal <- workflow_lineal %>%\n  fit_resamples(resamples = folds_cv, metrics = metricas_regresion)\n\ncollect_metrics(cv_lineal)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|.metric |.estimator |      mean|  n|   std_err|.config         |\n|:-------|:----------|---------:|--:|---------:|:---------------|\n|mae     |standard   | 0.2810335|  5| 0.0025914|pre0_mod0_post0 |\n|rmse    |standard   | 0.3533270|  5| 0.0033149|pre0_mod0_post0 |\n|rsq     |standard   | 0.7616462|  5| 0.0162058|pre0_mod0_post0 |\n\n</div>\n:::\n:::\n\n\nPara XGBoost dejamos que `tune_grid()` genere una grilla automática de 12 combinaciones de hiperparámetros (`grid = 12`), evaluando cada una con validación cruzada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\ntuning_xgb <- workflow_xgb %>%\n  tune_grid(resamples = folds_cv,\n            grid = 12,\n            metrics = metricas_regresion)\n```\n:::\n\n\nLa siguiente gráfica (`autoplot`) resume el tuning: muestra el RMSE de validación cruzada (en escala log) para cada combinación de hiperparámetros probada. Buscamos la región con menor RMSE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(tuning_xgb, metric = \"rmse\")\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-22-1.png){width=768}\n:::\n:::\n\n\nExtraemos la mejor combinación de hiperparámetros según el RMSE de validación cruzada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmejor_xgb <- tuning_xgb %>% select_best(metric = \"rmse\")\nmejor_xgb\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| tree_depth| learn_rate| loss_reduction|.config          |\n|----------:|----------:|--------------:|:----------------|\n|          1|  0.0657933|      0.0000169|pre0_mod01_post0 |\n\n</div>\n:::\n:::\n\n\n## 8. Implementar el workflow final de cada modelo\n\nLa regresión lineal ya está lista. A XGBoost le **inyectamos** los hiperparámetros ganadores con `finalize_workflow()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworkflow_xgb_final <- workflow_xgb %>%\n  finalize_workflow(mejor_xgb)\n```\n:::\n\n\n## 9. Entrenar y evaluar con last_fit() sobre la prueba\n\n::: {.callout-note collapse=\"true\"}\n## ¿Qué hace last_fit()?\n`last_fit()` toma el split original, **reentrena** el modelo final sobre TODO el entrenamiento y lo evalúa **una sola vez** sobre la base de prueba reservada. Es el paso que da la estimación honesta del desempeño en datos que el modelo nunca vio. Como la receta modela `log(costo)`, las métricas que devuelve `last_fit()` están **en escala log**.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_lineal <- workflow_lineal %>%\n  last_fit(split = costos_split, metrics = metricas_regresion)\n\najuste_xgb <- workflow_xgb_final %>%\n  last_fit(split = costos_split, metrics = metricas_regresion)\n```\n:::\n\n\n## 10. Pruebas del modelo: métricas y comparación\n\nReunimos las métricas en dos escalas. Primero, la tabla en **escala log**, que es la que `last_fit()` entrega directamente. Útil para diagnóstico, pero el RMSE y el MAE aquí no se leen en pesos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 10.1 Métricas en escala LOG (las que devuelve last_fit directamente).\nmetricas_log <- bind_rows(\n    collect_metrics(ajuste_lineal) %>% mutate(modelo = \"Regresión lineal\"),\n    collect_metrics(ajuste_xgb) %>% mutate(modelo = \"XGBoost\")\n  ) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(rmse)\n\nmetricas_log\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |      rmse|       rsq|       mae|\n|:----------------|---------:|---------:|---------:|\n|Regresión lineal | 0.3360094| 0.7724906| 0.2620346|\n|XGBoost          | 0.3473334| 0.7569920| 0.2682840|\n\n</div>\n:::\n:::\n\n\nAhora la **reconversión a pesos**, que es lo que realmente importa para el negocio. `collect_predictions()` devuelve `.pred` y la objetivo, ambas en escala log; al exponenciarlas (`exp`) volvemos a pesos y recalculamos el RMSE/MAE en esas unidades interpretables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 10.2 Reconversión a PESOS. collect_predictions devuelve .pred y la objetivo\n# en escala log; las exponenciamos para tener el error en pesos, que es lo\n# interpretable para el negocio.\npreds_lineal <- collect_predictions(ajuste_lineal) %>%\n  mutate(modelo = \"Regresión lineal\")\npreds_xgb <- collect_predictions(ajuste_xgb) %>%\n  mutate(modelo = \"XGBoost\")\n\npreds_ambos <- bind_rows(preds_lineal, preds_xgb) %>%\n  mutate(pred_pesos = exp(.pred),\n         real_pesos = exp(costo_anual_mxn))\n```\n:::\n\n\nCon las predicciones ya en pesos, calculamos las métricas por modelo en esa escala. **Esta es la tabla de decisión**: el RMSE en pesos es el error que se entiende en términos del problema.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Métricas en pesos por modelo.\nmetricas_pesos <- preds_ambos %>%\n  group_by(modelo) %>%\n  metricas_regresion(truth = real_pesos, estimate = pred_pesos) %>%\n  select(modelo, .metric, .estimate) %>%\n  pivot_wider(names_from = .metric, values_from = .estimate) %>%\n  arrange(rmse)\n\nmetricas_pesos\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |     rmse|       rsq|      mae|\n|:----------------|--------:|---------:|--------:|\n|Regresión lineal | 21440.20| 0.7260999| 12863.61|\n|XGBoost          | 22331.86| 0.7059068| 13367.15|\n\n</div>\n:::\n:::\n\n\nPara visualizar la calidad de cada modelo, graficamos los valores reales contra los predichos **en pesos**. La diagonal roja es la predicción perfecta: entre más pegados los puntos a la línea, mejor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reales vs. predichos en PESOS.\npreds_ambos %>%\n  ggplot(aes(x = real_pesos, y = pred_pesos)) +\n  geom_point(alpha = 0.4, color = \"#1e4c7d\") +\n  geom_abline(color = \"#c0392b\", linetype = 2) +\n  facet_wrap(~ modelo) +\n  labs(title = \"Costo real vs. predicho en pesos (base de prueba)\",\n       x = \"Costo real (MXN)\", y = \"Costo predicho (MXN)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-29-1.png){width=768}\n:::\n:::\n\n\nPor último, la gráfica de **importancia de variables** (`vip`) de XGBoost. Mide cuánto contribuye cada predictor a reducir el error en el conjunto de árboles: las barras más largas son las variables que más pesan en la predicción del costo. Es la forma estándar de interpretar un modelo de boosting, que de otro modo es una \"caja negra\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste_xgb %>%\n  extract_fit_parsnip() %>%\n  vip::vip(num_features = 12) +\n  labs(title = \"Importancia de variables — XGBoost\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](ejercicio_files/figure-html/unnamed-chunk-30-1.png){width=768}\n:::\n:::\n\n\n## Interpretación\n\n- Modelar `log(costo)` corrige el sesgo a la derecha: las métricas en escala log son más estables, pero **el error interpretable es el de pesos**, que obtenemos exponenciando las predicciones.\n- La **regresión lineal** sobre el log equivale a un modelo multiplicativo en pesos (cada predictor escala el costo); es interpretable.\n- **XGBoost** capta interacciones (p. ej. el efecto combinado de ser fumador y tener IMC alto) y suele predecir mejor. La importancia de variables confirma que `fumador` es el principal driver del costo.\n- Comparamos ambos en pesos con RMSE/MAE; el de menor error es el preferido.\n\n## Veredicto: ¿cuál es el mejor modelo?\n\nLa decisión se toma sobre las **métricas en pesos** (tabla `metricas_pesos`), no sobre las de escala log: el costo en pesos es la unidad que el negocio entiende, y un modelo puede verse parejo en log y separarse al reconvertir por culpa de la cola de costos altos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ordenamos por RMSE en PESOS (menor es mejor) y medimos la diferencia relativa\n# entre el mejor y el segundo, para juzgar si la ventaja es relevante o marginal.\ntabla_final <- metricas_pesos %>%\n  arrange(rmse) %>%\n  mutate(across(where(is.numeric), ~ round(., 2)))\n\nganador <- tabla_final %>% slice(1)\nperdedor <- tabla_final %>% slice(2)\ndif_rel_pct <- round(100 * (perdedor$rmse - ganador$rmse) / perdedor$rmse, 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tabla comparativa final en pesos (ordenada del mejor al peor por RMSE)\ntabla_final\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|modelo           |     rmse|  rsq|      mae|\n|:----------------|--------:|----:|--------:|\n|Regresión lineal | 21440.20| 0.73| 12863.61|\n|XGBoost          | 22331.86| 0.71| 13367.15|\n\n</div>\n:::\n:::\n\n\n**Modelo recomendado: Regresión lineal.** Obtiene el menor RMSE en pesos sobre la base de prueba (21440.2 MXN) con un R² de 0.73, frente a 22331.86 MXN del modelo xgboost. Su RMSE es **4% menor**.\n\n> La ventaja de **Regresión lineal** es relevante (4% en RMSE en pesos), por lo que es la elección clara para este problema.\n\nRecuerda que la regresión lineal sobre el log es la más fácil de interpretar (un coeficiente por variable, con efecto multiplicativo sobre el costo), mientras que XGBoost capta interacciones y no linealidades a costa de ser una caja negra; la gráfica de importancia de variables ayuda a abrirla y entender qué predictores mandan.\n",
    "supporting": [
      "ejercicio_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}